/* ═══════════════════════════════════════════════════════════════
   MERUVA Consulting · TRANG CHỦ — nội dung 3 ngôn ngữ

   Trang chủ mới (tư vấn ứng dụng AI · ROI) là một site KHÁC HẲN site
   cũ. File meruva_lang.js chỉ chứa bản dịch của site cũ (hệ sinh thái,
   coffee, bakery, thuê phòng) nên không dùng lại được — đây là bộ chữ
   riêng cho trang chủ, viết mới hoàn toàn.

   Theo đúng nếp của các trang mới khác (kitchen-lang.js, thietke-lang.js):
   gán vào window.MERUVA_T, nạp TRƯỚC meruva.js.

   Quy ước khoá:
     nav_*   thanh điều hướng      hero_*  khối mở đầu
     dg_*    sơ đồ kéo trượt       fig_*   thanh số
     s1..s8  nhãn/tiêu đề 8 mục    sig_*   bốn dấu hiệu
     pil_*   ba trụ cột            step_*  bốn bước lộ trình
     work_*  sản phẩm đã dựng      qb_*    bộ câu hỏi
     bin_*   phần giới thiệu Bin   vow_*   cam kết
     plan_*  ba gói dịch vụ        bk_*, f_* đặt lịch & biểu mẫu
     br_*    khung nhánh           ft_*    chân trang

   Chuỗi có thẻ HTML (<b> <em> <span class="c"> <br>) là cố ý — trang
   gán bằng innerHTML nên thẻ vẫn ăn.
   ═══════════════════════════════════════════════════════════════ */
window.MERUVA_T = {

/* ════════════════════════════════════════════════════════════════
   TIẾNG VIỆT
   ════════════════════════════════════════════════════════════════ */
vi: {
  page_title: 'MERUVA Consulting — Tư vấn ứng dụng AI và đo lường ROI',
  meta_desc: 'Biết chính xác nên ứng dụng AI ở đâu, triển khai theo lộ trình nào và đo được ROI — thay vì chỉ mua thêm công cụ. Tư vấn 1:1 tại TP.HCM.',

  brand_sub: 'Consulting · AI &amp; ROI',
  nav_signs: 'Dấu hiệu', nav_how: 'Cách làm', nav_work: 'Sản phẩm',
  nav_faq: 'Câu hỏi', nav_svc: 'Dịch vụ', nav_book: 'Đặt lịch',
  aria_burger: 'Mở menu', aria_road: 'Các bước trong lộ trình', aria_branches: 'Các nhánh của MERUVA',

  /* ── mở đầu ── */
  hero_lbl: 'Tư vấn ứng dụng AI cho doanh nghiệp · TP.HCM',
  hero_t1: 'Mua thêm', hero_t2: 'công cụ AI', hero_t3: 'không phải là', hero_t4: 'chiến lược AI.',
  hero_lead: 'MERUVA giúp bạn biết chính xác nên ứng dụng AI <b>ở đâu</b>, triển khai theo <b>lộ trình nào</b>, và <b>đo lường được ROI</b>.',
  hero_cta1: 'Đặt buổi rà soát AI',
  hero_cta2: 'Xem sản phẩm đã dựng',
  hero_fine: 'Buổi đầu tiên bạn nhận bản đồ điểm ứng dụng và con số nền để đo ROI — kể cả khi không làm tiếp với MERUVA.',

  /* ── sơ đồ kéo trượt ── */
  dg_title: 'Ứng dụng AI trong doanh nghiệp',
  dg_state_a: 'Mua rời rạc', dg_state_b: 'Đang sắp lại…', dg_state_c: 'Có lộ trình · đo được',
  dg_end1: 'Rời rạc', dg_end2: 'Có lộ trình · đo được',
  dg_hint: '← kéo thanh trượt →',
  dg_lane1: 'Điểm ứng dụng', dg_lane2: 'Lộ trình', dg_lane3: 'Đo ROI',
  dg_node_you: 'Bạn', dg_node_trial: 'Bản dùng thử', dg_node_new: 'Tool mới',
  dg_aria: 'Sơ đồ minh hoạ: các công cụ AI mua rời rạc, mọi thứ đổ về một người và không đo được, chuyển thành ba làn có thứ tự — Điểm ứng dụng, Lộ trình, Đo ROI.',
  dg_slider_aria: 'Kéo để xem doanh nghiệp trước và sau khi có lộ trình AI',

  /* ── câu định vị ── */
  stance_idx: 'Định vị',
  stance_p: 'Chúng tôi giúp doanh nghiệp biết chính xác nên ứng dụng AI <b>ở đâu</b>, triển khai theo <b>lộ trình nào</b> và <b>đo lường được ROI</b><span class="neg"> — thay vì chỉ mua thêm công cụ AI.</span>',
  stance_by: 'MERUVA Consulting · Phạm Duy Kha (Bin)',

  /* ── thanh số ── */
  fig1_k: 'nhánh kinh doanh<br>Bin đang tự vận hành',
  fig2_k: 'sản phẩm đã dựng<br>mở xem được ngay',
  fig3_k: 'trực tiếp với Bin<br>không qua trung gian',
  fig4_k: 'giờ — thời gian<br>phản hồi lịch hẹn',

  /* ── 01 · dấu hiệu ── */
  s1_lbl: 'Rà soát',
  s1_h2: 'Bạn thấy mình ở đâu trong bốn dấu hiệu này?',
  s1_lead: 'Không phải doanh nghiệp nào cũng cần làm AI ngay. Chạm vào những dòng đúng với bạn.',
  sig1_t: 'Đã trả tiền vài công cụ AI, nhưng ít ai dùng',
  sig1_d: 'Mua theo phong trào, dùng sôi nổi hai tuần rồi nguội. Không ai biết cái nào còn đang bị trừ tiền hằng tháng.',
  sig2_t: 'Không nói được AI đang tiết kiệm bao nhiêu',
  sig2_d: 'Cảm giác là có nhanh hơn. Nhưng không có số giờ công, không có số nền trước khi dùng, nên không ai chứng minh được gì.',
  sig3_t: 'Mỗi người tự xài một kiểu AI riêng',
  sig3_d: 'Người dùng bản miễn phí, người dùng bản trả phí, dữ liệu công ty đi vào những nơi không ai kiểm soát. Không có quy định chung.',
  sig4_t: 'Biết phải làm AI, nhưng không biết bắt đầu ở đâu',
  sig4_d: 'Đọc nhiều, nghe nhiều, sợ chậm chân. Nhưng chưa ai chỉ ra trong doanh nghiệp bạn thì việc nào đáng làm trước, việc nào chưa tới lúc.',
  sig_m0: 'Chọn những dấu hiệu đúng với doanh nghiệp bạn.<span class="c">Cả bốn đều cùng một gốc: AI được mua trước khi được đặt đúng chỗ.</span>',
  sig_m1: 'Một dấu hiệu — vẫn còn xử lý được bằng nội lực.<span class="c">Nhưng nó hiếm khi đứng một mình lâu.</span>',
  sig_m2: 'Hai dấu hiệu trở lên — bạn đang trả tiền cho AI mà không biết nó đáng bao nhiêu.<span class="c">Đây là lúc một buổi rà soát có ích nhất: có bản đồ điểm ứng dụng và số nền để đo.</span>',
  sig_m3: 'Ba dấu hiệu — AI đang là một khoản chi, chưa phải một khoản đầu tư.<span class="c">Khác biệt giữa hai thứ đó nằm ở chỗ có đo được hay không.</span>',
  sig_m4: 'Cả bốn — vấn đề không nằm ở công cụ. Nằm ở chỗ chưa ai chỉ ra nên đặt AI vào đâu trong doanh nghiệp bạn.<span class="c">Bắt đầu từ buổi rà soát: 90 phút, có bản đồ điểm ứng dụng mang về.</span>',
  sig_cta: 'Đặt buổi rà soát AI',

  /* ── 02 · ba vế ── */
  s2_lbl: 'Cách làm',
  s2_h2: 'Ba câu hỏi phải trả lời trước khi chi đồng nào cho AI.',
  s2_lead: 'Bỏ qua bất kỳ vế nào cũng dẫn tới cùng một kết cục: một khoản chi hằng tháng không ai bảo vệ được khi bị hỏi.',
  pil1_q: 'Vế 01 — Ở đâu?', pil1_h3: 'Điểm ứng dụng',
  pil1_l1: 'Kiểm kê công cụ AI đang trả tiền &amp; ai thật sự dùng',
  pil1_l2: 'Đo giờ công đang tiêu ở từng luồng việc',
  pil1_l3: 'Chấm điểm: tiết kiệm bao nhiêu × dễ làm tới đâu',
  pil1_l4: 'Loại thẳng những việc AI chưa nên đụng vào',
  pil2_q: 'Vế 02 — Theo lộ trình nào?', pil2_h3: 'Thứ tự triển khai',
  pil2_l1: 'Bắt đầu từ một việc thắng nhanh, thấy kết quả trong tuần',
  pil2_l2: 'Quy định dùng AI &amp; phân loại dữ liệu được phép',
  pil2_l3: 'Đào tạo theo vai trò, không đào tạo đại trà',
  pil2_l4: 'Mở rộng chỉ khi việc trước đã thật sự chạy',
  pil3_q: 'Vế 03 — Đo bằng gì?', pil3_h3: 'Thước đo ROI',
  pil3_l1: 'Chốt con số nền <em>trước</em> khi triển khai',
  pil3_l2: 'Giờ công tiết kiệm mỗi tuần, quy ra tiền',
  pil3_l3: 'Chi phí công cụ so với phần cắt được',
  pil3_l4: 'Bảng theo dõi để bạn tự đọc, không cần hỏi Bin',
  pil_note: 'Thiếu vế "ở đâu", bạn tự động hoá nhầm việc. Thiếu vế "lộ trình", đội ngũ bỏ cuộc ở tuần thứ ba. <b>Thiếu vế "ROI", bạn không bao giờ biết khoản chi đó nên tăng hay nên cắt.</b>',

  /* ── 03 · lộ trình ── */
  s3_lbl: 'Lộ trình',
  s3_h2: 'Từ buổi rà soát đến con số ROI đầu tiên.',
  s3_lead: 'Bạn biết mình đang ở bước nào, nhận được gì ở cuối mỗi bước, và có quyền dừng sau bất kỳ bước nào.',
  road1: 'Rà soát &amp; chấm điểm', road2: 'Chọn điểm &amp; chốt số nền',
  road3: 'Triển khai thí điểm', road4: 'Đo ROI &amp; nhân rộng',
  step_out_b: 'Bạn nhận',
  step1_h3: 'Rà soát &amp; chấm điểm', step1_when: '90 phút · tại chỗ hoặc online',
  step1_p: 'Bin ngồi cùng bạn và một hai người vận hành chính: kiểm kê công cụ AI đang trả tiền, đo giờ công đang tiêu ở từng luồng việc, rồi chấm điểm từng việc theo mức tiết kiệm và độ khó.',
  step1_out: 'Bản đồ điểm ứng dụng AI, xếp theo thứ tự đáng làm trước.',
  step2_h3: 'Chọn điểm &amp; chốt số nền', step2_when: '1 – 2 tuần',
  step2_p: 'Chọn một tới hai việc làm trước, viết business case cho từng việc, và chốt con số nền trước khi đụng vào bất cứ thứ gì. Không có số nền thì sau này không thể nói AI có hiệu quả hay không.',
  step2_out: 'Business case + con số nền đã chốt + quy định dùng AI và phân loại dữ liệu.',
  step3_h3: 'Triển khai thí điểm', step3_when: '2 – 6 tuần',
  step3_p: 'Bin dựng tận tay trên một luồng việc thật, đào tạo đúng những người sẽ dùng nó hằng ngày, rồi sửa cho vừa trước khi nhân rộng. Ưu tiên dùng sâu công cụ bạn đã có trước khi mua thêm.',
  step3_out: 'Luồng việc chạy thật + hướng dẫn theo vai trò + automation đã bật.',
  step4_h3: 'Đo ROI &amp; nhân rộng', step4_when: '14 – 30 ngày sau khi chạy',
  step4_p: 'So số thật với số nền: giờ công tiết kiệm, chi phí cắt được, thời gian hoàn tất luồng việc. Có số rồi mới quyết định mở rộng — hoặc dừng lại nếu số không thuyết phục.',
  step4_out: 'Báo cáo ROI đọc được trong một phút + bảng theo dõi bạn tự cập nhật.',

  /* ── 04 · sản phẩm thật ── */
  s4_lbl: 'Bằng chứng',
  s4_h2: 'Đây là thứ Bin đã dựng. Mở ra bấm thử được.',
  s4_lead: 'Không phải ảnh chụp màn hình, không phải mockup. Năm sản phẩm dưới đây đang chạy thật — bấm vào là mở bản đầy đủ, tương tác trực tiếp trên máy bạn.',
  work_skel: 'đang tải bản xem trước…',
  work_open: 'Mở bản đầy đủ ↗',
  work1_d: 'Dashboard quản lý khách hàng: pipeline, hoạt động, báo cáo trên một màn hình.',
  work2_d: 'Không gian làm việc cá nhân kiểu Notion — dự án, lĩnh vực, nhịp review.',
  work3_d: 'Theo dõi mức năng lượng trong ngày để xếp việc vào đúng khung giờ.',
  work4_d: 'Ứng dụng sức khoẻ &amp; chu kỳ, thiết kế riêng cho người dùng nữ.',
  work5_d: 'Theo dõi dinh dưỡng và tập luyện, tính khẩu phần theo mục tiêu.',
  works_note: 'Hai sản phẩm đầu là công cụ vận hành. Ba cái sau Bin dựng cho chính mình và người nhà dùng hằng ngày — không phải bài tập cho đẹp hồ sơ. Đó cũng là cách Bin làm việc với doanh nghiệp: dựng thứ chạy được rồi mới nói chuyện mở rộng.',

  /* ── 05 · bộ câu hỏi ── */
  s5_lbl: 'Bộ câu hỏi',
  s5_h2: 'Những câu doanh nghiệp thật sự đang mắc.',
  s5_lead: 'Đây là các câu lặp đi lặp lại mỗi khi Bin ngồi xuống với một chủ doanh nghiệp. Gom lại một chỗ, trả lời thẳng — để bạn đọc trước, khỏi mất buổi tư vấn chỉ để hỏi những điều này.',
  qb_all: 'Tất cả', qb_start: 'Bắt đầu', qb_money: 'Chi phí &amp; ROI',
  qb_data: 'Dữ liệu &amp; rủi ro', qb_team: 'Con người', qb_tool: 'Công cụ',
  qb_bar_aria: 'Lọc câu hỏi theo nhóm',
  qb_n_all: ' câu hỏi', qb_n_one: ' câu trong nhóm này',
  qb_empty: 'Không có câu hỏi nào trong nhóm này.',
  qb_foot: 'Câu của bạn chưa có ở đây? Ghi vào ô cuối trang khi đặt lịch — Bin trả lời trong buổi rà soát, và câu đó sẽ được bổ sung vào danh sách này.',
  qb_foot_link: 'Đặt câu hỏi của bạn →',

  q1_q: 'Chúng tôi nên bắt đầu từ phòng ban nào?',
  q1_a: 'Không bắt đầu từ phòng ban — bắt đầu từ <em>luồng việc</em>. Việc đáng làm trước là việc lặp lại nhiều lần mỗi tuần, tốn giờ công thật, và nếu AI làm chưa chuẩn thì hậu quả nhẹ, sửa được. Rất thường xuyên việc đó nằm vắt ngang hai ba phòng ban, nên chọn theo phòng ban sẽ chọn nhầm.',
  q2_q: 'Doanh nghiệp tôi mới 8 người, làm AI có sớm quá không?',
  q2_a: 'Ngược lại. Ở quy mô này mỗi giờ tiết kiệm được chiếm tỷ trọng lớn trong tổng năng lực, và cả đội học xong trong một buổi. Doanh nghiệp 50–100 người tốn gấp nhiều lần cho cùng một việc, vì phải gỡ thói quen cũ trước khi dựng cái mới.',
  q3_q: 'Ngành của tôi khá đặc thù, AI có áp dụng được không?',
  q3_a: 'Phần việc được tự động hoá thường không đặc thù bằng ngành: soạn báo giá, trả lời câu hỏi lặp lại của khách, tổng hợp số cuối ngày, viết mô tả sản phẩm, dịch tài liệu. Bin bắt đầu từ những việc đó, không bắt đầu từ phần chuyên môn cốt lõi của bạn.',
  q4_q: 'Cần chuẩn bị gì trước buổi rà soát?',
  q4_a: 'Không cần chuẩn bị tài liệu. Chỉ cần có mặt bạn và một hai người đang trực tiếp làm việc mỗi ngày. Nếu tiện, mang theo danh sách các công cụ đang trả phí — nhưng không có cũng không sao, Bin dựng lại được trong buổi.',
  q5_q: 'Bao lâu thì thấy kết quả đầu tiên?',
  q5_a: 'Ngay buổi rà soát bạn đã có bản đồ điểm ứng dụng — nhiều chủ doanh nghiệp nói đây là lần đầu họ nhìn thấy toàn cảnh. Một luồng việc thật thường chạy được sau 2 đến 6 tuần triển khai, tuỳ độ phức tạp.',
  q6_q: 'Chi phí AI hằng tháng thực tế là bao nhiêu?',
  q6_a: 'Với doanh nghiệp dưới 20 người, phần lớn chi phí là tài khoản trả phí cho vài người dùng chính — không phải cho toàn công ty. Một trong những việc của bước lộ trình là xác định chính xác ai cần bản trả phí, ai dùng bản miễn phí là đủ. Rất nhiều nơi đang trả cho cả công ty trong khi chỉ ba người dùng thật.',
  q7_q: 'Làm sao biết AI có đáng tiền hay không?',
  q7_a: 'So với con số nền được chốt <em>trước</em> khi triển khai. Ba nhóm số: giờ công tiết kiệm mỗi tuần quy ra tiền, chi phí trực tiếp cắt được, và thời gian hoàn tất một luồng việc từ đầu tới cuối. Không có số nền thì mọi lời khen AI về sau đều chỉ là cảm giác.',
  q8_q: 'Nếu đo xong mà số không thuyết phục?',
  q8_a: 'Thì dừng, và đó là một kết quả tốt — bạn biết điều đó sau vài tuần thay vì sau một năm trả phí. Bin nói thẳng khi một điểm ứng dụng không đáng làm tiếp, và bạn có quyền dừng sau bất kỳ bước nào trong lộ trình.',
  q9_q: 'Có cần đầu tư máy chủ hay hạ tầng gì không?',
  q9_a: 'Trong đại đa số trường hợp doanh nghiệp vừa và nhỏ: không. Mọi thứ chạy trên dịch vụ sẵn có và công cụ bạn đang dùng. Chỉ khi dữ liệu thuộc nhóm không được phép rời khỏi công ty thì mới bàn tới phương án chạy nội bộ — và khi đó Bin nói rõ chi phí trước.',
  q10_q: 'Đưa dữ liệu công ty vào AI có an toàn không?',
  q10_a: 'An toàn hay không phụ thuộc <em>dữ liệu nào</em> và <em>công cụ nào</em>. Bin phân loại dữ liệu của bạn theo mức nhạy cảm trước, rồi mới quyết định nhóm nào được đưa vào AI và trên gói nào. Bản miễn phí và bản doanh nghiệp có chính sách rất khác nhau về việc dữ liệu của bạn có bị dùng để huấn luyện hay không.',
  q11_q: 'AI trả lời sai thì ai chịu trách nhiệm?',
  q11_a: 'Doanh nghiệp bạn, luôn luôn. Vì vậy nguyên tắc là: những việc mà sai sót gây hậu quả nghiêm trọng thì AI chỉ được làm nháp, người duyệt cuối. Việc phân định chỗ nào AI tự chạy, chỗ nào phải có người ký, nằm ngay trong quy định dùng AI ở bước lộ trình.',
  q12_q: 'Có cần dữ liệu sạch trước khi làm AI không?',
  q12_a: 'Không cần sạch toàn bộ — đó là cái bẫy khiến nhiều doanh nghiệp trì hoãn mãi. Chỉ cần sạch ở đúng luồng việc được chọn làm trước. Dọn dữ liệu cho một luồng việc mất vài ngày; dọn toàn bộ có thể mất cả năm và thường không bao giờ xong.',
  q13_q: 'Khách hàng biết chúng tôi dùng AI thì sao?',
  q13_a: 'Tuỳ chỗ dùng. Với việc nội bộ như tổng hợp báo cáo, không ai quan tâm. Với nội dung gửi trực tiếp tới khách, nguyên tắc của Bin là luôn có người đọc lại và chịu trách nhiệm — vì khách nhận ra văn bản máy viết nhanh hơn ta tưởng, và mất điểm ở đó không đáng.',
  q14_q: 'AI có thay thế nhân sự của tôi không?',
  q14_a: 'Trong phần lớn doanh nghiệp vừa và nhỏ, AI thay <em>phần việc</em> chứ không thay người: nhập liệu, soạn thảo lặp lại, tổng hợp báo cáo. Bin thiết kế để đội ngũ làm được nhiều hơn với cùng số người — và nói rõ điều đó với đội ngay buổi đào tạo đầu tiên. Đội ngũ sợ bị thay thế là lý do phổ biến nhất khiến một dự án AI chết yểu.',
  q15_q: 'Đội ngũ lớn tuổi, ngại công nghệ thì sao?',
  q15_a: 'Hệ thống được cắt theo trình độ đội ngũ hiện tại, không theo thứ Bin thích dùng. Nếu đội bạn đang chạy trên Zalo và Excel thì bắt đầu ngay trên Zalo và Excel. Và cách hiệu quả nhất là chọn một người trong đội làm trước, thấy nhẹ hẳn, rồi chính họ kéo người khác — nhanh hơn mọi buổi đào tạo.',
  q16_q: 'Ai trong công ty nên phụ trách AI?',
  q16_a: 'Không cần người biết công nghệ. Cần một người hiểu quy trình, có uy tín trong đội, và đủ thẩm quyền để nói "từ nay việc này làm theo cách mới". Bin kèm cặp trực tiếp người đó trong suốt thời gian đồng hành để sau này bạn không phụ thuộc vào Bin.',
  q17_q: 'Đào tạo mất bao lâu?',
  q17_a: 'Đào tạo theo vai trò, mỗi vai trò thường một tới hai buổi ngắn cộng với một video quay riêng để xem lại. Bin không đào tạo đại trà cả công ty cùng lúc — kiểu đó ai cũng nghe và không ai áp dụng.',
  q18_q: 'Chúng tôi đã mua vài công cụ AI rồi thì sao?',
  q18_a: 'Tốt, đó là dữ liệu. Bin bắt đầu bằng việc kiểm kê những gì bạn đang trả tiền và xem cái nào thật sự có người dùng. Rất thường xuyên, bước đầu tiên là cắt bớt và dùng sâu hơn thứ đã có — chứ không phải mua thêm cái mới.',
  q19_q: 'Nên dùng ChatGPT, Gemini hay Copilot?',
  q19_a: 'Câu trả lời phụ thuộc bạn đang làm việc trên nền nào và dữ liệu nào được phép đưa vào — không có đáp án chung. Thường thì công cụ gắn liền với bộ văn phòng bạn đang dùng sẽ thắng, đơn giản vì đội ngũ không phải đổi thói quen. Bin chọn công cụ ở bước lộ trình, sau khi đã biết điểm ứng dụng.',
  q20_q: 'Có cần đặt làm phần mềm riêng không?',
  q20_a: 'Hiếm khi cần, và gần như không bao giờ ở giai đoạn đầu. Đặt làm phần mềm riêng tốn tiền và tốn thời gian trong khi bạn còn chưa chắc điểm ứng dụng đó có ROI. Làm chạy được bằng công cụ có sẵn trước, đo, rồi mới tính chuyện đầu tư sâu hơn.',

  /* ── 06 · Bin ── */
  s6_lbl: 'Người làm',
  s6_h2: 'Người đã tự chạy AI trong doanh nghiệp của chính mình.',
  port_ph: 'Chỗ dành cho ảnh chân dung Bin<br>— cần một tấm thật',
  port_cap: 'Phạm Duy Kha (Bin)<br>Sáng lập MERUVA · TP.HCM',
  bin_q: 'Công cụ AI thì ai mua cũng được. Cái khó là biết đặt nó vào đúng chỗ, và dám đo xem nó có đáng tiền không.',
  bin_p1: 'Năm năm làm việc trong môi trường Nhật để lại cho Bin ba thói quen: <em>genchi genbutsu</em> — xuống tận nơi nhìn việc thật trước khi kết luận; <em>kaizen</em> — cải tiến từng bước nhỏ đo được, thay vì làm một cú lớn; và thói quen chốt con số trước khi bắt đầu. Ba thói quen đó là toàn bộ cách MERUVA tiếp cận AI hôm nay.',
  bin_p2: 'Bin cũng đang tự vận hành bốn nhánh kinh doanh nhỏ của chính mình — cà phê &amp; bánh, thiết kế, cho thuê studio, thẻ thành viên. Mỗi điểm ứng dụng AI đề xuất cho khách đều đã chạy ở đó trước: có việc thành, có việc bỏ, và cả hai đều là dữ liệu.',
  creed1_h4: 'Xuống tận nơi, nhìn việc thật',
  creed1_p: 'Không tư vấn AI qua bản mô tả công việc. Bin ngồi cạnh người đang làm, xem họ thao tác, rồi mới nói AI nên chen vào chỗ nào.',
  creed2_h4: 'Dùng sâu trước khi mua thêm',
  creed2_p: 'Bước đầu tiên thường là cắt bớt, không phải mua thêm. Rất nhiều doanh nghiệp đã trả tiền cho thứ mình chưa dùng hết 20%.',
  creed3_h4: 'Không có số nền thì không triển khai',
  creed3_p: 'Nếu không đo được trạng thái trước, sau này mọi lời khen AI đều chỉ là cảm giác. Số nền được chốt ngay buổi rà soát.',

  /* ── 07 · cam kết ── */
  s7_lbl: 'Cam kết',
  s7_h2: 'Bạn không cần đặt cược gì ở bước đầu.',
  s7_lead: 'Ba điều dưới đây áp dụng cho mọi khách, không cần hỏi.',
  vow1_h3: 'Dừng sau bất kỳ bước nào',
  vow1_p: 'Lộ trình chia bốn bước rời nhau. Hết mỗi bước bạn quyết định đi tiếp hay dừng — không ràng buộc trọn gói, không phí huỷ.',
  vow2_h3: 'Bản đồ là của bạn',
  vow2_p: 'Bản đồ điểm ứng dụng và con số nền từ buổi rà soát thuộc về bạn — kể cả khi bạn quyết định tự làm hoặc thuê bên khác triển khai.',
  vow3_h3: 'Báo giá chốt trước khi bắt đầu',
  vow3_p: 'Giá triển khai được chốt bằng con số cố định sau buổi rà soát, trước khi làm. Không tính theo giờ, không phát sinh giữa chừng.',

  /* ── 08 · dịch vụ ── */
  s8_lbl: 'Dịch vụ',
  s8_h2: 'Ba cách làm việc với MERUVA Consulting.',
  s8_lead: 'Mọi gói đều trực tiếp với Bin. Chạm vào từng dòng để xem chi tiết. Đặt lịch chưa cần thanh toán — Bin xác nhận trong 24 giờ rồi mới gửi hướng dẫn.',
  tier_h: 'Doanh nghiệp',
  plan1_name: 'Buổi rà soát AI',
  plan1_tag: '90 phút · tại chỗ hoặc online — khi bạn biết phải làm AI nhưng chưa biết bắt đầu ở đâu',
  plan1_price: 'Trao đổi riêng', plan1_cta: 'Đặt lịch',
  plan1_d1: '90 phút cùng bạn &amp; người vận hành chính',
  plan1_d2: 'Kiểm kê công cụ AI đang trả tiền',
  plan1_d3: 'Bản đồ điểm ứng dụng đã chấm điểm',
  plan1_d4: 'Con số nền để sau này đo ROI',
  plan1_d5: 'Đề xuất bước tiếp theo — không ràng buộc',
  plan1_d6: 'Follow-up 7 ngày qua Zalo',
  plan2_name: 'Triển khai AI trọn gói', plan2_pop: 'Được chọn nhiều nhất',
  plan2_tag: 'Rà soát → chốt số nền → triển khai thí điểm → báo cáo ROI, Bin làm tận tay cùng đội ngũ bạn',
  plan2_price: 'Báo giá theo quy mô', plan2_cta: 'Nhận báo giá',
  plan2_d1: 'Trọn bộ bốn bước của lộ trình',
  plan2_d2: 'Business case cho từng điểm ứng dụng',
  plan2_d3: 'Quy định dùng AI &amp; phân loại dữ liệu',
  plan2_d4: 'Dựng trên công cụ phù hợp đội bạn',
  plan2_d5: 'Đào tạo theo vai trò, tận tay',
  plan2_d6: 'Báo cáo ROI so với số nền đã chốt',
  plan3_name: 'Đồng hành theo tháng',
  plan3_tag: 'Cho doanh nghiệp đã chạy điểm đầu tiên — cần người giữ nhịp mở rộng và canh con số',
  plan3_price: 'Trao đổi riêng', plan3_cta: 'Trao đổi',
  plan3_d1: 'Nhịp review ROI hằng tháng',
  plan3_d2: 'Mở rộng sang điểm ứng dụng tiếp theo',
  plan3_d3: 'Rà soát chi phí công cụ, cắt phần thừa',
  plan3_d4: 'Cập nhật khi công cụ AI đổi tính năng',
  plan3_d5: 'Kèm cặp người phụ trách AI nội bộ',
  plan3_d6: 'Huỷ bất kỳ tháng nào, không ràng buộc',

  /* ── đặt lịch ── */
  bk_idx: 'Bắt đầu', bk_lbl: 'Đặt lịch',
  bk_h2: 'Một buổi rà soát là có bản đồ mang về.',
  bk_lead: 'Điền vào đây, Bin xác nhận trong 24 giờ. Chưa cần thanh toán ở bước này.',
  ci_email_k: 'Email', ci_web_k: 'Website',
  ci_area_k: 'Khu vực', ci_area_v: 'TP.HCM · online toàn quốc',
  ci_hours_k: 'Giờ phản hồi', ci_hours_v: 'Mỗi ngày · 7:00 → 22:00',
  after_h: 'Sau khi bạn gửi',
  after1: 'Bin đọc và phản hồi trong 24 giờ, qua Zalo hoặc điện thoại.',
  after2: 'Hai bên chốt giờ và hình thức — tại chỗ hoặc online.',
  after3: 'Bin gửi hướng dẫn thanh toán sau khi lịch đã xác nhận.',
  f_name: 'Tên của bạn *', f_phone: 'Điện thoại / Zalo *',
  f_service: 'Bạn quan tâm', f_date: 'Ngày mong muốn',
  f_opt1: 'Buổi rà soát AI · 90 phút', f_opt2: 'Triển khai AI trọn gói · dự án',
  f_opt3: 'Đồng hành theo tháng · retainer', f_opt4: 'Chưa rõ — cần tư vấn thêm',
  f_note: 'Câu hỏi của bạn, hoặc việc đang tốn thời gian nhất',
  f_note_ph: 'Quy mô đội ngũ, ngành nghề, công cụ AI đang dùng (nếu có)...',
  f_submit: 'Gửi yêu cầu đặt lịch →',
  f_ok: 'Đã nhận. Bin sẽ phản hồi trong 24 giờ — cảm ơn bạn đã tin tưởng.',
  form_sending: 'Đang gửi...',
  form_err: 'Có lỗi xảy ra. Vui lòng thử lại.',
  form_neterr: 'Không gửi được. Kiểm tra kết nối và thử lại.',

  /* ── khung nhánh + chân trang ── */
  br_kind1: '· 4 nhánh Bin tự vận hành',
  br_design: 'Thiết kế',
  br_partner: 'Đối tác',
  br_vemil_d: 'Sữa hạt &amp; thực phẩm vegan · thủ công',
  ft_news: 'Báo', ft_copy: '© 2026 MERUVA'
},

/* ════════════════════════════════════════════════════════════════
   ENGLISH
   ════════════════════════════════════════════════════════════════ */
en: {
  page_title: 'MERUVA Consulting — AI adoption advice, with measurable ROI',
  meta_desc: 'Know exactly where AI belongs in your business, in what order to roll it out, and how to measure the ROI — instead of just buying more tools. 1:1 advisory in Ho Chi Minh City.',

  brand_sub: 'Consulting · AI &amp; ROI',
  nav_signs: 'Signs', nav_how: 'Method', nav_work: 'Work',
  nav_faq: 'Questions', nav_svc: 'Services', nav_book: 'Book',
  aria_burger: 'Open menu', aria_road: 'Roadmap steps', aria_branches: 'MERUVA branches',

  hero_lbl: 'AI adoption advisory for businesses · Ho Chi Minh City',
  hero_t1: 'Buying more', hero_t2: 'AI tools', hero_t3: 'is not', hero_t4: 'an AI strategy.',
  hero_lead: 'MERUVA helps you find out exactly <b>where</b> AI belongs, <b>in what order</b> to roll it out, and how to <b>measure the ROI</b>.',
  hero_cta1: 'Book an AI review',
  hero_cta2: 'See what has been built',
  hero_fine: 'From the first session you walk away with a map of where AI fits and the baseline numbers to measure ROI — even if you never work with MERUVA again.',

  dg_title: 'AI adoption inside a business',
  dg_state_a: 'Bought piecemeal', dg_state_b: 'Falling into place…', dg_state_c: 'Sequenced · measurable',
  dg_end1: 'Piecemeal', dg_end2: 'Sequenced · measurable',
  dg_hint: '← drag the slider →',
  dg_lane1: 'Where it fits', dg_lane2: 'Rollout order', dg_lane3: 'ROI measured',
  dg_node_you: 'You', dg_node_trial: 'Free trial', dg_node_new: 'New tool',
  dg_aria: 'Illustration: AI tools bought piecemeal, everything funnelling through one person with nothing measured, rearranging into three ordered lanes — Where it fits, Rollout order, ROI measured.',
  dg_slider_aria: 'Drag to compare the business before and after it has an AI roadmap',

  stance_idx: 'Position',
  stance_p: 'We help businesses find out exactly <b>where</b> AI belongs, <b>in what order</b> to roll it out, and how to <b>measure the ROI</b><span class="neg"> — instead of just buying more AI tools.</span>',
  stance_by: 'MERUVA Consulting · Pham Duy Kha (Bin)',

  fig1_k: 'businesses Bin<br>runs himself',
  fig2_k: 'products built<br>open them right now',
  fig3_k: 'directly with Bin<br>no middlemen',
  fig4_k: 'hours — booking<br>response time',

  s1_lbl: 'Self-check',
  s1_h2: 'Which of these four signs sounds like you?',
  s1_lead: 'Not every business needs AI right now. Tap the lines that match yours.',
  sig1_t: 'Paying for several AI tools, but few people use them',
  sig1_d: 'Bought because everyone else was. Two lively weeks, then silence. Nobody is quite sure which ones are still being charged every month.',
  sig2_t: 'Cannot say how much AI is actually saving',
  sig2_d: 'It feels faster. But there are no hours logged and no baseline from before, so nobody can prove anything either way.',
  sig3_t: 'Everyone uses AI their own way',
  sig3_d: 'Some on the free plan, some on paid, company data flowing into places nobody is watching. No shared rules.',
  sig4_t: 'You know you should do AI, but not where to start',
  sig4_d: 'Plenty read, plenty heard, and a fear of falling behind. But nobody has told you which task in your business is worth doing first, and which one can wait.',
  sig_m0: 'Tap the signs that match your business.<span class="c">All four share one root: AI gets bought before it gets placed.</span>',
  sig_m1: 'One sign — still manageable in-house.<span class="c">Though it rarely stays alone for long.</span>',
  sig_m2: 'Two or more — you are paying for AI without knowing what it is worth.<span class="c">This is when a review helps most: you get a map of where AI fits and a baseline to measure against.</span>',
  sig_m3: 'Three signs — AI is a cost right now, not an investment.<span class="c">The difference between the two comes down to whether it is measured.</span>',
  sig_m4: 'All four — the problem is not the tools. It is that nobody has shown you where AI belongs in your business.<span class="c">Start with a review: 90 minutes, and you leave with the map.</span>',
  sig_cta: 'Book an AI review',

  s2_lbl: 'Method',
  s2_h2: 'Three questions to answer before spending a cent on AI.',
  s2_lead: 'Skip any one of them and you land in the same place: a monthly cost nobody can defend when asked about it.',
  pil1_q: 'Part 01 — Where?', pil1_h3: 'Where it fits',
  pil1_l1: 'Audit the AI tools being paid for &amp; who actually uses them',
  pil1_l2: 'Measure the hours each workflow currently eats',
  pil1_l3: 'Score each one: how much it saves × how easy it is',
  pil1_l4: 'Rule out the work AI should not touch yet',
  pil2_q: 'Part 02 — In what order?', pil2_h3: 'Rollout order',
  pil2_l1: 'Start with one quick win visible within the week',
  pil2_l2: 'Rules for using AI &amp; which data is allowed in',
  pil2_l3: 'Train by role, not the whole company at once',
  pil2_l4: 'Expand only once the previous step genuinely runs',
  pil3_q: 'Part 03 — Measured how?', pil3_h3: 'The ROI yardstick',
  pil3_l1: 'Lock in the baseline <em>before</em> anything is rolled out',
  pil3_l2: 'Hours saved per week, converted into money',
  pil3_l3: 'Tool costs against what was actually cut',
  pil3_l4: 'A tracker you read yourself, without asking Bin',
  pil_note: 'Skip "where" and you automate the wrong task. Skip "order" and the team gives up in week three. <b>Skip "ROI" and you will never know whether that spending should grow or stop.</b>',

  s3_lbl: 'Roadmap',
  s3_h2: 'From the first review to your first ROI number.',
  s3_lead: 'You always know which step you are on, what you get at the end of it, and you can stop after any step.',
  road1: 'Review &amp; score', road2: 'Pick a target &amp; set the baseline',
  road3: 'Pilot rollout', road4: 'Measure ROI &amp; scale',
  step_out_b: 'You get',
  step1_h3: 'Review &amp; score', step1_when: '90 minutes · on-site or online',
  step1_p: 'Bin sits down with you and one or two of the people who actually run things: audits the AI tools being paid for, measures the hours each workflow eats, then scores every task by how much it saves and how hard it is.',
  step1_out: 'A map of where AI fits, ordered by what is worth doing first.',
  step2_h3: 'Pick a target &amp; set the baseline', step2_when: '1 – 2 weeks',
  step2_p: 'Choose one or two tasks to go first, write a business case for each, and lock in the baseline before touching anything. Without a baseline, there is no way to say later whether AI worked.',
  step2_out: 'Business case + agreed baseline + rules for using AI and classifying data.',
  step3_h3: 'Pilot rollout', step3_when: '2 – 6 weeks',
  step3_p: 'Bin builds it hands-on inside one real workflow, trains exactly the people who will use it daily, then adjusts the fit before anything scales. Getting more out of the tools you already own comes before buying new ones.',
  step3_out: 'A workflow genuinely running + role-based guides + automation switched on.',
  step4_h3: 'Measure ROI &amp; scale', step4_when: '14 – 30 days after go-live',
  step4_p: 'Compare the real numbers against the baseline: hours saved, costs cut, time to finish the workflow. Only with numbers in hand do you decide to expand — or to stop, if they are not convincing.',
  step4_out: 'An ROI report readable in one minute + a tracker you update yourself.',

  s4_lbl: 'Evidence',
  s4_h2: 'This is what Bin has built. Open it and click around.',
  s4_lead: 'Not screenshots, not mockups. The five products below are genuinely running — click one and the full version opens, interactive, on your own machine.',
  work_skel: 'loading preview…',
  work_open: 'Open full version ↗',
  work1_d: 'Customer management dashboard: pipeline, activity and reporting on one screen.',
  work2_d: 'A Notion-style personal workspace — projects, areas, review rhythm.',
  work3_d: 'Tracks energy levels through the day so work lands in the right hours.',
  work4_d: 'Health &amp; cycle app, designed specifically for women.',
  work5_d: 'Nutrition and training tracker, with portions calculated against your goal.',
  works_note: 'The first two are operational tools. The last three Bin built for himself and his own family to use daily — not portfolio exercises. That is also how Bin works with businesses: build something that runs, then talk about scaling it.',

  s5_lbl: 'Question bank',
  s5_h2: 'The questions businesses are genuinely stuck on.',
  s5_lead: 'These come up every time Bin sits down with a business owner. Gathered in one place and answered straight — so you can read them beforehand and not spend a consultation asking them.',
  qb_all: 'All', qb_start: 'Getting started', qb_money: 'Cost &amp; ROI',
  qb_data: 'Data &amp; risk', qb_team: 'People', qb_tool: 'Tools',
  qb_bar_aria: 'Filter questions by group',
  qb_n_all: ' questions', qb_n_one: ' in this group',
  qb_empty: 'No questions in this group.',
  qb_foot: 'Your question not here? Write it in the last field when you book — Bin answers it during the review, and it gets added to this list.',
  qb_foot_link: 'Ask your question →',

  q1_q: 'Which department should we start with?',
  q1_a: 'Do not start with a department — start with a <em>workflow</em>. The task worth doing first is the one repeated many times a week, eating real hours, where a rough AI answer causes light, fixable damage. Very often that task cuts across two or three departments, so choosing by department picks the wrong thing.',
  q2_q: 'We are only 8 people. Is it too early for AI?',
  q2_a: 'The opposite. At this size every hour saved is a large share of total capacity, and the whole team learns it in one sitting. A 50–100 person company spends many times more on the same task, because old habits have to be undone before anything new goes in.',
  q3_q: 'My industry is quite specific. Does AI even apply?',
  q3_a: 'The work that gets automated is usually far less industry-specific than the industry itself: drafting quotes, answering repeat customer questions, compiling end-of-day numbers, writing product descriptions, translating documents. Bin starts there, not with your core expertise.',
  q4_q: 'What should we prepare before the review?',
  q4_a: 'No documents needed. Just you and one or two people doing the work every day. Bring a list of the tools you pay for if it is handy — but if not, Bin can reconstruct it during the session.',
  q5_q: 'How long until we see the first result?',
  q5_a: 'You already have the map of where AI fits by the end of the review — many owners say it is the first time they have seen the whole picture. A real workflow usually runs after 2 to 6 weeks of rollout, depending on complexity.',
  q6_q: 'What does AI actually cost per month?',
  q6_a: 'For a business under 20 people, most of the cost is paid seats for a few key users — not the whole company. Part of the roadmap step is working out exactly who needs a paid plan and who is fine on free. Plenty of places are paying for everyone while only three people genuinely use it.',
  q7_q: 'How do we know whether AI is worth the money?',
  q7_a: 'Against a baseline locked in <em>before</em> rollout. Three groups of numbers: hours saved per week converted into money, direct costs cut, and the end-to-end time to finish a workflow. Without a baseline, every later compliment about AI is just a feeling.',
  q8_q: 'What if we measure and the numbers are not convincing?',
  q8_a: 'Then you stop, and that is a good outcome — you learned it in a few weeks instead of after a year of subscriptions. Bin says plainly when a use case is not worth continuing, and you can stop after any step of the roadmap.',
  q9_q: 'Do we need to invest in servers or infrastructure?',
  q9_a: 'For the vast majority of small and mid-sized businesses: no. Everything runs on existing services and the tools you already use. Only when data is in a category that must not leave the company do we discuss running things in-house — and Bin states that cost upfront.',
  q10_q: 'Is it safe to put company data into AI?',
  q10_a: 'Safe or not depends on <em>which data</em> and <em>which tool</em>. Bin classifies your data by sensitivity first, then decides which groups may go into AI and on which plan. Free and business tiers have very different policies on whether your data is used for training.',
  q11_q: 'If AI answers wrongly, who is responsible?',
  q11_a: 'Your business, always. Which is why the rule is: for work where a mistake causes serious damage, AI only drafts and a person signs off. Deciding where AI runs on its own and where a human must approve sits inside the AI usage rules from the roadmap step.',
  q12_q: 'Do we need clean data before doing AI?',
  q12_a: 'Not clean everywhere — that is the trap that keeps businesses postponing forever. It only needs to be clean in the one workflow chosen to go first. Cleaning data for a single workflow takes days; cleaning everything can take a year and usually never finishes.',
  q13_q: 'What if customers find out we use AI?',
  q13_a: 'Depends where. For internal work like compiling reports, nobody minds. For anything sent straight to a customer, Bin insists a person reads it and owns it — customers spot machine-written text faster than we assume, and losing credibility there is not worth it.',
  q14_q: 'Will AI replace my staff?',
  q14_a: 'In most small and mid-sized businesses, AI replaces <em>parts of the work</em>, not people: data entry, repetitive drafting, compiling reports. Bin designs it so the same team gets more done — and says so plainly to the team in the very first training session. A team afraid of being replaced is the most common reason an AI project dies early.',
  q15_q: 'Our team is older and wary of technology. What then?',
  q15_a: 'The system is cut to fit the team you have, not the tools Bin happens to like. If your team runs on Zalo and Excel, it starts on Zalo and Excel. And the most effective route is one person trying it first, feeling the relief, then pulling the others along — faster than any training session.',
  q16_q: 'Who inside the company should own AI?',
  q16_a: 'Not someone technical. Someone who understands the process, has credibility with the team, and enough authority to say "from now on we do it this way". Bin coaches that person directly throughout, so you do not end up dependent on Bin.',
  q17_q: 'How long does training take?',
  q17_a: 'Training is by role — usually one or two short sessions per role plus a recorded video to revisit. Bin does not train the whole company at once; that way everyone listens and nobody applies it.',
  q18_q: 'We have already bought some AI tools. What now?',
  q18_a: 'Good, that is data. Bin starts by auditing what you are paying for and which of it genuinely has users. Very often the first step is cutting back and getting more out of what you own — not buying something new.',
  q19_q: 'Should we use ChatGPT, Gemini or Copilot?',
  q19_a: 'It depends which platform you already work on and which data is allowed in — there is no universal answer. Usually the tool tied to your existing office suite wins, simply because the team does not have to change habits. Bin picks tools at the roadmap step, after the use cases are known.',
  q20_q: 'Do we need custom software built?',
  q20_a: 'Rarely, and almost never at the start. Custom software costs money and time while you are still unsure that use case has any ROI. Get it running on off-the-shelf tools first, measure it, and only then consider investing deeper.',

  s6_lbl: 'Who does the work',
  s6_h2: 'Someone who has run AI inside his own business first.',
  port_ph: 'Space for a portrait of Bin<br>— a real one is needed',
  port_cap: 'Pham Duy Kha (Bin)<br>Founder of MERUVA · Ho Chi Minh City',
  bin_q: 'Anyone can buy an AI tool. The hard part is knowing where to put it, and being willing to measure whether it was worth the money.',
  bin_p1: 'Five years working in a Japanese environment left Bin with three habits: <em>genchi genbutsu</em> — go and see the actual work before concluding anything; <em>kaizen</em> — small measurable improvements rather than one big swing; and the habit of agreeing the numbers before starting. Those three habits are the whole of how MERUVA approaches AI today.',
  bin_p2: 'Bin also runs four small businesses of his own — coffee &amp; bakery, design, studio rentals, a membership card. Every AI use case proposed to a client has already been run there first: some worked, some were dropped, and both are data.',
  creed1_h4: 'Go and see the actual work',
  creed1_p: 'No advising on AI from a job description. Bin sits beside the person doing the work, watches how they do it, and only then says where AI should step in.',
  creed2_h4: 'Go deeper before buying more',
  creed2_p: 'The first step is usually cutting back, not adding. Plenty of businesses are already paying for something they use less than 20% of.',
  creed3_h4: 'No baseline, no rollout',
  creed3_p: 'If the before state was never measured, every later compliment about AI is just a feeling. The baseline is agreed during the review itself.',

  s7_lbl: 'Commitments',
  s7_h2: 'You are not betting anything at the first step.',
  s7_lead: 'The three below apply to every client, no need to ask.',
  vow1_h3: 'Stop after any step',
  vow1_p: 'The roadmap is four separate steps. At the end of each you decide whether to continue or stop — no all-or-nothing package, no cancellation fee.',
  vow2_h3: 'The map is yours',
  vow2_p: 'The map of where AI fits and the baseline numbers from the review belong to you — including if you decide to do it yourself or hire someone else to roll it out.',
  vow3_h3: 'Price agreed before work starts',
  vow3_p: 'The rollout price is agreed as a fixed number after the review, before any work begins. Not hourly, and nothing added along the way.',

  s8_lbl: 'Services',
  s8_h2: 'Three ways to work with MERUVA Consulting.',
  s8_lead: 'Every option is directly with Bin. Tap any row for details. Booking requires no payment — Bin confirms within 24 hours and only then sends instructions.',
  tier_h: 'For businesses',
  plan1_name: 'AI review session',
  plan1_tag: '90 minutes · on-site or online — for when you know you should do AI but not where to begin',
  plan1_price: 'Let us talk', plan1_cta: 'Book',
  plan1_d1: '90 minutes with you &amp; whoever runs operations',
  plan1_d2: 'Audit of the AI tools being paid for',
  plan1_d3: 'A scored map of where AI fits',
  plan1_d4: 'Baseline numbers to measure ROI against later',
  plan1_d5: 'A recommended next step — no obligation',
  plan1_d6: '7 days of follow-up over Zalo',
  plan2_name: 'Full AI rollout', plan2_pop: 'Most chosen',
  plan2_tag: 'Review → baseline → pilot rollout → ROI report, with Bin building hands-on alongside your team',
  plan2_price: 'Quoted by scope', plan2_cta: 'Get a quote',
  plan2_d1: 'All four steps of the roadmap',
  plan2_d2: 'A business case for every use case',
  plan2_d3: 'AI usage rules &amp; data classification',
  plan2_d4: 'Built on tools that suit your team',
  plan2_d5: 'Hands-on training, by role',
  plan2_d6: 'ROI report against the agreed baseline',
  plan3_name: 'Monthly retainer',
  plan3_tag: 'For businesses already past their first use case — needing someone to keep the expansion moving and watch the numbers',
  plan3_price: 'Let us talk', plan3_cta: 'Talk to Bin',
  plan3_d1: 'A monthly ROI review rhythm',
  plan3_d2: 'Expanding into the next use case',
  plan3_d3: 'Auditing tool spend, cutting the excess',
  plan3_d4: 'Updates when AI tools change what they do',
  plan3_d5: 'Coaching your internal AI owner',
  plan3_d6: 'Cancel any month, no lock-in',

  bk_idx: 'Start here', bk_lbl: 'Book',
  bk_h2: 'One review and the map is yours to keep.',
  bk_lead: 'Fill this in and Bin confirms within 24 hours. No payment at this stage.',
  ci_email_k: 'Email', ci_web_k: 'Website',
  ci_area_k: 'Area', ci_area_v: 'Ho Chi Minh City · online nationwide',
  ci_hours_k: 'Response hours', ci_hours_v: 'Every day · 7:00 → 22:00',
  after_h: 'After you send',
  after1: 'Bin reads it and replies within 24 hours, by Zalo or phone.',
  after2: 'You agree a time and format together — on-site or online.',
  after3: 'Bin sends payment instructions once the booking is confirmed.',
  f_name: 'Your name *', f_phone: 'Phone / Zalo *',
  f_service: 'What interests you', f_date: 'Preferred date',
  f_opt1: 'AI review session · 90 minutes', f_opt2: 'Full AI rollout · project',
  f_opt3: 'Monthly retainer', f_opt4: 'Not sure yet — need advice',
  f_note: 'Your question, or whatever is eating the most time right now',
  f_note_ph: 'Team size, industry, AI tools already in use (if any)...',
  f_submit: 'Send booking request →',
  f_ok: 'Received. Bin will reply within 24 hours — thank you for the trust.',
  form_sending: 'Sending...',
  form_err: 'Something went wrong. Please try again.',
  form_neterr: 'Could not send. Check your connection and try again.',

  br_kind1: '· 4 businesses Bin runs himself',
  br_design: 'Design',
  br_partner: 'Partner',
  br_vemil_d: 'Plant milk &amp; vegan food · handmade',
  ft_news: 'Journal', ft_copy: '© 2026 MERUVA'
},

/* ════════════════════════════════════════════════════════════════
   日本語
   ════════════════════════════════════════════════════════════════ */
ja: {
  page_title: 'MERUVA Consulting — AI活用の導入支援とROI測定',
  meta_desc: 'AIをどこに使うべきか、どの順番で導入するか、ROIをどう測るか。ツールを買い足すだけで終わらせないための1対1コンサルティング（ホーチミン市）。',

  brand_sub: 'Consulting · AI &amp; ROI',
  nav_signs: '兆候', nav_how: '進め方', nav_work: '制作物',
  nav_faq: 'よくある質問', nav_svc: 'サービス', nav_book: '予約',
  aria_burger: 'メニューを開く', aria_road: 'ロードマップの各段階', aria_branches: 'MERUVAの事業一覧',

  hero_lbl: '企業向けAI活用コンサルティング · ホーチミン市',
  hero_t1: 'AIツールを', hero_t2: '買い足すことは', hero_t3: 'AI戦略では', hero_t4: 'ありません。',
  hero_lead: 'MERUVAは、AIを<b>どこに</b>使うべきか、<b>どの順番で</b>導入するか、そして<b>ROIをどう測るか</b>を明確にします。',
  hero_cta1: 'AI診断を予約する',
  hero_cta2: '制作物を見る',
  hero_fine: '初回で、AIの活用ポイントを示した地図とROI測定の基準値をお持ち帰りいただけます。その後MERUVAに依頼されない場合でも同じです。',

  dg_title: '企業におけるAI活用',
  dg_state_a: 'ばらばらに購入', dg_state_b: '整理中…', dg_state_c: '順序があり測定できる',
  dg_end1: 'ばらばら', dg_end2: '順序があり測定できる',
  dg_hint: '← スライダーを動かす →',
  dg_lane1: '活用ポイント', dg_lane2: '導入の順番', dg_lane3: 'ROI測定',
  dg_node_you: 'あなた', dg_node_trial: '無料版', dg_node_new: '新ツール',
  dg_aria: '図：ばらばらに購入されたAIツールがすべて一人に集中し測定もされていない状態から、活用ポイント・導入の順番・ROI測定という三つの流れに整理されるまで。',
  dg_slider_aria: 'ドラッグして、AIロードマップ導入前後の状態を比較',

  stance_idx: '立ち位置',
  stance_p: '私たちは、AIを<b>どこに</b>使うべきか、<b>どの順番で</b>導入するか、そして<b>ROIをどう測るか</b>を明確にします<span class="neg">。AIツールを買い足すのではなく。</span>',
  stance_by: 'MERUVA Consulting · ファム・ズイ・カー（Bin）',

  fig1_k: '事業をBin自身が<br>運営しています',
  fig2_k: '制作した product<br>今すぐ開けます',
  fig3_k: 'Binが直接担当<br>仲介はありません',
  fig4_k: '時間 — 予約への<br>返信までの目安',

  s1_lbl: '自己診断',
  s1_h2: 'この四つの兆候、どれが当てはまりますか。',
  s1_lead: 'すべての企業が今すぐAIを導入すべきとは限りません。当てはまる項目に触れてみてください。',
  sig1_t: 'AIツールに払っているが、使う人が少ない',
  sig1_d: '流行に乗って導入し、二週間は盛り上がったものの、その後は静か。どれがまだ毎月引き落とされているのか誰も把握していない。',
  sig2_t: 'AIがいくら節約できているか言えない',
  sig2_d: '速くなった気はする。しかし工数の記録も導入前の基準値もないため、誰も何も証明できない。',
  sig3_t: '各自がばらばらの使い方をしている',
  sig3_d: '無料版の人、有料版の人が混在し、社内データが誰も管理していない場所へ流れていく。共通のルールがない。',
  sig4_t: 'やるべきとは分かるが、どこから始めるか分からない',
  sig4_d: '情報は十分に読み、聞いてもいる。出遅れる不安もある。しかし自社のどの業務を先にやるべきで、どれはまだ早いのかを誰も示してくれない。',
  sig_m0: '自社に当てはまる兆候を選んでください。<span class="c">四つとも根は同じです。置き場所が決まる前にAIが買われている、ということ。</span>',
  sig_m1: '一つ — まだ自力で対処できる段階です。<span class="c">ただし、これが一つのままでいることは稀です。</span>',
  sig_m2: '二つ以上 — 価値が分からないままAIに支払っている状態です。<span class="c">診断が最も効くのはこの時点です。活用ポイントの地図と、測るための基準値が手に入ります。</span>',
  sig_m3: '三つ — 今のAIは投資ではなく、単なる費用です。<span class="c">その二つを分けるのは、測定できているかどうかだけです。</span>',
  sig_m4: '四つすべて — 問題はツールではありません。自社のどこにAIを置くべきかを、まだ誰も示していないことです。<span class="c">まず診断から。90分で、活用ポイントの地図をお持ち帰りいただけます。</span>',
  sig_cta: 'AI診断を予約する',

  s2_lbl: '進め方',
  s2_h2: 'AIに一円でも使う前に答えるべき三つの問い。',
  s2_lead: 'どれか一つでも飛ばすと、行き着く先は同じです。問われたとき誰も説明できない毎月の支出になります。',
  pil1_q: '問い01 — どこに？', pil1_h3: '活用ポイント',
  pil1_l1: '支払い中のAIツールと、実際の利用者を棚卸しする',
  pil1_l2: '各業務フローが今どれだけ工数を食っているか測る',
  pil1_l3: '採点する：削減効果 × 実行しやすさ',
  pil1_l4: 'AIがまだ触るべきでない業務を明確に外す',
  pil2_q: '問い02 — どの順番で？', pil2_h3: '導入の順番',
  pil2_l1: '一週間で成果が見える小さな成功から始める',
  pil2_l2: 'AI利用ルールと、入力してよいデータの区分を定める',
  pil2_l3: '全社一斉ではなく、役割ごとに研修する',
  pil2_l4: '前の一つが本当に回ってから次へ広げる',
  pil3_q: '問い03 — 何で測る？', pil3_h3: 'ROIの物差し',
  pil3_l1: '導入<em>前</em>に基準値を確定させる',
  pil3_l2: '週あたりの削減工数を、金額に換算する',
  pil3_l3: 'ツール費用と、実際に削減できた額を比べる',
  pil3_l4: 'Binに聞かずご自身で読める管理表',
  pil_note: '「どこに」が抜けると、間違った業務を自動化します。「順番」が抜けると、三週目でチームが離脱します。<b>「ROI」が抜けると、その支出を増やすべきか止めるべきか、永遠に分かりません。</b>',

  s3_lbl: 'ロードマップ',
  s3_h2: '診断から、最初のROIの数字まで。',
  s3_lead: '今どの段階にいて、その終わりに何を受け取るのかが常に分かります。どの段階の後でも中止できます。',
  road1: '診断と採点', road2: '対象の選定と基準値の確定',
  road3: '試験導入', road4: 'ROI測定と展開',
  step_out_b: 'お渡しするもの',
  step1_h3: '診断と採点', step1_when: '90分 · 訪問またはオンライン',
  step1_p: 'Binがあなたと、実際に現場を回している一〜二名と一緒に座ります。支払い中のAIツールを棚卸しし、各業務フローの工数を測り、削減効果と難易度で一つずつ採点します。',
  step1_out: 'AI活用ポイントの地図。先に着手すべき順に並べたもの。',
  step2_h3: '対象の選定と基準値の確定', step2_when: '1〜2週間',
  step2_p: '先に着手する業務を一〜二件選び、それぞれのビジネスケースを書き、何かに手をつける前に基準値を確定させます。基準値がなければ、後からAIが効いたかどうかを語ることはできません。',
  step2_out: 'ビジネスケース＋確定した基準値＋AI利用ルールとデータ区分。',
  step3_h3: '試験導入', step3_when: '2〜6週間',
  step3_p: 'Binが実際の業務フロー一つに自ら手を入れて構築し、毎日使う人だけを対象に研修し、展開前に運用に合うよう調整します。新規購入より先に、すでにあるツールを使い込むことを優先します。',
  step3_out: '実際に回る業務フロー＋役割別の手順書＋稼働済みの自動化。',
  step4_h3: 'ROI測定と展開', step4_when: '稼働から14〜30日後',
  step4_p: '実績を基準値と比べます。削減工数、削減できた費用、業務フロー完了までの時間。数字が出てから展開を決めます。納得できない数字なら、そこで止めます。',
  step4_out: '一分で読めるROIレポート＋ご自身で更新できる管理表。',

  s4_lbl: '実物',
  s4_h2: 'これがBinの制作物です。開いて触れます。',
  s4_lead: 'スクリーンショットでもモックアップでもありません。以下の五つは実際に動いています。クリックすれば完全版が開き、お手元の端末で操作できます。',
  work_skel: 'プレビューを読み込み中…',
  work_open: '完全版を開く ↗',
  work1_d: '顧客管理ダッシュボード：パイプライン、活動履歴、レポートを一画面に。',
  work2_d: 'Notion型の個人ワークスペース。プロジェクト、領域、振り返りの周期。',
  work3_d: '一日のエネルギー水準を記録し、業務を適した時間帯に配置するためのもの。',
  work4_d: '女性向けに設計した健康＆周期管理アプリ。',
  work5_d: '栄養と運動の記録。目標に合わせて分量を計算します。',
  works_note: '前の二つは業務用ツールです。後の三つはBin自身と家族が毎日使うために作ったもので、見栄えのための課題ではありません。企業との仕事も同じ進め方です。まず動くものを作り、それから展開の話をします。',

  s5_lbl: '質問集',
  s5_h2: '企業が実際に詰まっている質問。',
  s5_lead: 'Binが経営者と向き合うたびに繰り返し出る質問です。一箇所にまとめ、率直に答えました。事前に読んでいただければ、これらを聞くためだけに相談時間を使わずに済みます。',
  qb_all: 'すべて', qb_start: '始め方', qb_money: '費用とROI',
  qb_data: 'データとリスク', qb_team: '人', qb_tool: 'ツール',
  qb_bar_aria: '質問を分類で絞り込む',
  qb_n_all: ' 件の質問', qb_n_one: ' 件（この分類）',
  qb_empty: 'この分類に質問はありません。',
  qb_foot: 'お探しの質問がありませんか。ご予約時の最後の欄にお書きください。診断の場でBinがお答えし、この一覧にも追加されます。',
  qb_foot_link: '質問を送る →',

  q1_q: 'どの部署から始めるべきですか。',
  q1_a: '部署からではなく、<em>業務フロー</em>から始めます。先に着手すべきなのは、週に何度も繰り返され、実際に工数を食っていて、AIの精度が粗くても被害が軽く修正できる業務です。そうした業務は二〜三の部署にまたがっていることが多く、部署単位で選ぶと外します。',
  q2_q: '社員8名ですが、AIはまだ早いでしょうか。',
  q2_a: '逆です。この規模では削減できた一時間が全体の能力に占める割合が大きく、チーム全員が一度の説明で習得できます。50〜100名の企業は同じことに何倍もかかります。新しいものを入れる前に、古い習慣を外す作業が必要になるからです。',
  q3_q: '業界が特殊ですが、AIは適用できますか。',
  q3_a: '自動化される業務は、業界そのものほど特殊ではないことがほとんどです。見積書の作成、繰り返される顧客からの質問への回答、日次の数字の集計、商品説明の作成、資料の翻訳など。Binはそこから始めます。御社の中核業務からではありません。',
  q4_q: '診断の前に何を準備すればよいですか。',
  q4_a: '資料の準備は不要です。あなたと、毎日実務にあたっている一〜二名がいれば十分です。支払い中のツール一覧があればお持ちください。なくても構いません、その場で洗い出せます。',
  q5_q: '最初の成果はどのくらいで出ますか。',
  q5_a: '診断の時点で、活用ポイントの地図はお渡しできます。全体像を初めて見たとおっしゃる経営者が多くいます。実際の業務フローが回り始めるのは、複雑さにもよりますが導入から2〜6週間が目安です。',
  q6_q: '毎月のAI費用は実際いくらですか。',
  q6_a: '20名未満の企業では、費用の大半は主要な数名分の有料アカウントであり、全社分ではありません。誰に有料版が必要で、誰は無料版で足りるのかを見極めるのも、ロードマップ段階の仕事です。実際に使うのは三人だけなのに全社分を払っている例は少なくありません。',
  q7_q: 'AIが費用に見合うかは、どう判断しますか。',
  q7_a: '導入<em>前</em>に確定させた基準値と比べます。数字は三種類です。週あたりの削減工数を金額換算したもの、直接削減できた費用、そして業務フローが最初から最後まで終わるまでの時間。基準値がなければ、後のAIへの称賛はすべて感覚にすぎません。',
  q8_q: '測ってみて数字が納得できなかったら。',
  q8_a: 'そこで止めます。それは良い結果です。一年課金し続けた後ではなく、数週間で分かったのですから。継続に値しない活用ポイントについてBinは率直に申し上げますし、ロードマップのどの段階の後でも中止できます。',
  q9_q: 'サーバーや基盤への投資は必要ですか。',
  q9_a: '中小企業の大半の場合、不要です。既存のサービスと、今お使いのツールの上で動きます。社外に出せない区分のデータを扱う場合にのみ、社内で動かす方式を検討します。その際は費用を事前に明示します。',
  q10_q: '社内データをAIに入れても安全ですか。',
  q10_a: '安全かどうかは<em>どのデータか</em>と<em>どのツールか</em>で決まります。Binはまず御社のデータを機密度で分類し、そのうえでどの区分をどのプランのAIに入れてよいかを決めます。無料版と法人版では、入力データが学習に使われるかどうかの方針が大きく異なります。',
  q11_q: 'AIが誤った回答をした場合、誰の責任ですか。',
  q11_a: '常に御社です。ですから原則はこうなります。誤りが重大な結果を招く業務では、AIは下書きまでとし、最終確認は人が行う。どこまでAIに任せ、どこから人の承認が要るのかの線引きは、ロードマップ段階のAI利用ルールに含まれます。',
  q12_q: 'AIの前にデータを整備する必要がありますか。',
  q12_a: '全体を整える必要はありません。それが多くの企業を先延ばしにさせる罠です。先に着手すると決めた業務フローの範囲だけ整っていれば十分です。一つの業務フロー分なら数日、全体となると一年かかることもあり、たいてい終わりません。',
  q13_q: 'AIを使っていると顧客に知られたら。',
  q13_a: '使う場所によります。レポート集計のような社内業務なら誰も気にしません。顧客へ直接届く内容については、必ず人が読み返し責任を持つというのがBinの原則です。機械が書いた文章は思うより早く気づかれますし、そこで信頼を損なう価値はありません。',
  q14_q: 'AIは社員の代わりになりますか。',
  q14_a: '中小企業の多くでは、AIが置き換えるのは人ではなく<em>作業</em>です。データ入力、繰り返しの文書作成、レポート集計など。Binは同じ人数でより多くを実現できるよう設計し、それを最初の研修でチームにはっきり伝えます。置き換えられる不安は、AI導入が頓挫する最も多い原因です。',
  q15_q: '年配のチームで、技術に抵抗があります。',
  q15_a: 'Binの好みではなく、今のチームの水準に合わせて設計します。ZaloとExcelで回っているなら、ZaloとExcelから始めます。そして最も効くのは、チームの一人が先に試し、楽になったと実感し、その人が周りを引っ張ることです。どんな研修より速く広がります。',
  q16_q: '社内では誰がAIの担当になるべきですか。',
  q16_a: '技術に詳しい人である必要はありません。業務を理解していて、チームからの信頼があり、「今後はこのやり方でいく」と言える権限がある人です。その方をBinが伴走期間中ずっと直接指導しますので、後々Binに依存せずに済みます。',
  q17_q: '研修にはどのくらいかかりますか。',
  q17_a: '役割ごとの研修で、通常は一役割につき短い回を一〜二度、加えて後から見返せる録画を一本お渡しします。全社一斉の研修はしません。あの形式は、全員が聞いて誰も実行しません。',
  q18_q: 'すでにAIツールをいくつか買っていますが。',
  q18_a: '結構です、それはデータになります。Binはまず、支払い中のものを棚卸しし、どれに実際の利用者がいるかを確認します。最初の一歩が「減らして、既にあるものを使い込む」になることは非常に多く、新規購入ではありません。',
  q19_q: 'ChatGPT、Gemini、Copilotのどれを使うべきですか。',
  q19_a: '今どの基盤の上で仕事をしていて、どのデータを入れてよいかで変わります。万能の答えはありません。多くの場合、既存のオフィス製品と一体になったツールが有利です。チームが習慣を変えずに済むからです。Binは活用ポイントが見えたロードマップ段階でツールを選びます。',
  q20_q: '専用ソフトを開発する必要はありますか。',
  q20_a: '必要な場面は稀で、初期段階ではほぼありません。その活用ポイントにROIがあるか確信できていない段階で、専用開発は費用も時間もかかります。まず既存ツールで動かし、測り、そのうえで踏み込んだ投資を検討します。',

  s6_lbl: '担当者',
  s6_h2: '自分の事業でAIを回してきた人間です。',
  port_ph: 'Binの人物写真を入れる場所<br>— 実物が必要です',
  port_cap: 'ファム・ズイ・カー（Bin）<br>MERUVA創業者 · ホーチミン市',
  bin_q: 'AIツールは誰でも買えます。難しいのは、正しい場所に置くことと、費用に見合うかを測る覚悟を持つことです。',
  bin_p1: '日本での五年間がBinに三つの習慣を残しました。<em>現地現物</em> — 結論を出す前に現場へ行き実際の仕事を見ること。<em>改善</em> — 大きな一手ではなく、測れる小さな改良を重ねること。そして、始める前に数字を決める習慣。この三つが、今のMERUVAのAIへの向き合い方のすべてです。',
  bin_p2: 'Bin自身も四つの小さな事業を運営しています。コーヒーとベーカリー、デザイン、スタジオ賃貸、会員カード。お客様に提案するAI活用ポイントは、すべて先にそこで試しています。うまくいったものも、やめたものもあり、どちらもデータです。',
  creed1_h4: '現場へ行き、実際の仕事を見る',
  creed1_p: '業務説明書だけを見てAIの助言はしません。Binは実務者の隣に座り、手の動きを見てから、AIをどこに入れるべきかを述べます。',
  creed2_h4: '買い足す前に、使い込む',
  creed2_p: '最初の一歩はたいてい、追加ではなく削減です。すでに持っているものを2割も使い切れていない企業は少なくありません。',
  creed3_h4: '基準値がなければ導入しない',
  creed3_p: '導入前の状態を測っていなければ、後のAIへの称賛はすべて感覚にすぎません。基準値は診断の場で確定させます。',

  s7_lbl: 'お約束',
  s7_h2: '最初の一歩で、賭けていただくものはありません。',
  s7_lead: '以下の三点は、お申し出がなくてもすべてのお客様に適用されます。',
  vow1_h3: 'どの段階の後でも中止できます',
  vow1_p: 'ロードマップは独立した四段階です。各段階の終わりに、続けるか止めるかをお決めいただけます。一括契約の縛りも、解約料もありません。',
  vow2_h3: '地図はお客様のものです',
  vow2_p: '診断で作成した活用ポイントの地図と基準値はお客様に帰属します。ご自身で進める場合も、他社に導入を依頼される場合も同じです。',
  vow3_h3: '着手前に金額を確定します',
  vow3_p: '導入費用は診断後、着手前に固定額で確定します。時間単価ではなく、途中での追加もありません。',

  s8_lbl: 'サービス',
  s8_h2: 'MERUVA Consultingとの三つの進め方。',
  s8_lead: 'いずれもBinが直接担当します。各行に触れると詳細が開きます。ご予約時の支払いは不要です。24時間以内にBinが確認し、その後にご案内します。',
  tier_h: '法人向け',
  plan1_name: 'AI診断セッション',
  plan1_tag: '90分 · 訪問またはオンライン — AIをやるべきとは分かるが、どこから始めるか分からない方へ',
  plan1_price: '個別にご相談', plan1_cta: '予約する',
  plan1_d1: 'あなたと現場責任者を交えた90分',
  plan1_d2: '支払い中のAIツールの棚卸し',
  plan1_d3: '採点済みの活用ポイントの地図',
  plan1_d4: '後日ROIを測るための基準値',
  plan1_d5: '次の一歩のご提案 — 契約義務なし',
  plan1_d6: 'Zaloでの7日間フォロー',
  plan2_name: 'AI導入一式', plan2_pop: '最も選ばれています',
  plan2_tag: '診断 → 基準値の確定 → 試験導入 → ROIレポート。Binが御社チームと共に自ら手を動かします',
  plan2_price: '規模に応じてお見積り', plan2_cta: '見積りを依頼',
  plan2_d1: 'ロードマップ四段階すべて',
  plan2_d2: '活用ポイントごとのビジネスケース',
  plan2_d3: 'AI利用ルールとデータ区分',
  plan2_d4: '御社チームに合うツールの上で構築',
  plan2_d5: '役割別の実地研修',
  plan2_d6: '確定した基準値と比べたROIレポート',
  plan3_name: '月次伴走',
  plan3_tag: '最初の活用ポイントが動き出した企業向け — 展開の歩調を保ち、数字を見る人が必要な方へ',
  plan3_price: '個別にご相談', plan3_cta: 'ご相談',
  plan3_d1: '月次のROI振り返り',
  plan3_d2: '次の活用ポイントへの展開',
  plan3_d3: 'ツール費用の見直しと無駄の削減',
  plan3_d4: 'AIツールの仕様変更時の更新',
  plan3_d5: '社内AI担当者への指導',
  plan3_d6: 'いつでも解約可、縛りなし',

  bk_idx: 'はじめに', bk_lbl: '予約',
  bk_h2: '一度の診断で、地図が手に入ります。',
  bk_lead: 'こちらにご記入ください。24時間以内にBinが確認します。この段階でのお支払いは不要です。',
  ci_email_k: 'メール', ci_web_k: 'ウェブサイト',
  ci_area_k: '対応地域', ci_area_v: 'ホーチミン市 · オンラインは全国',
  ci_hours_k: '返信時間', ci_hours_v: '毎日 · 7:00 → 22:00',
  after_h: '送信後の流れ',
  after1: 'Binが確認し、24時間以内にZaloまたは電話でご返信します。',
  after2: '日時と形式（訪問またはオンライン）を双方で決めます。',
  after3: '予約確定後に、Binがお支払い方法をご案内します。',
  f_name: 'お名前 *', f_phone: '電話 / Zalo *',
  f_service: 'ご関心のある内容', f_date: 'ご希望日',
  f_opt1: 'AI診断セッション · 90分', f_opt2: 'AI導入一式 · プロジェクト',
  f_opt3: '月次伴走', f_opt4: 'まだ未定 — 相談したい',
  f_note: 'ご質問、または今いちばん時間を取られている業務',
  f_note_ph: 'チームの人数、業種、すでに使っているAIツール（あれば）...',
  f_submit: '予約を申し込む →',
  f_ok: '受け付けました。24時間以内にBinよりご返信します。ありがとうございます。',
  form_sending: '送信中...',
  form_err: 'エラーが発生しました。もう一度お試しください。',
  form_neterr: '送信できませんでした。接続をご確認のうえ、再度お試しください。',

  br_kind1: '· Binが自ら運営する4事業',
  br_design: 'デザイン',
  br_partner: 'パートナー',
  br_vemil_d: 'ナッツミルク＆ヴィーガン食品 · 手づくり',
  ft_news: 'ジャーナル', ft_copy: '© 2026 MERUVA'
}

};
