/* ═══════════════════════════════════════════════════════════
   MERUVA 3D & DESIGN — Page-specific Language Strings
   Merge vào window.MERUVA_LANG khi trang load (xem inline script).
   Languages: vi · en · ja  ·  Prefix khóa: d3_
   ═══════════════════════════════════════════════════════════ */

window.MERUVA3D_LANG = {

/* ══════════════ TIẾNG VIỆT ══════════════ */
vi: {
  /* nav + footer links */
  d3_nav_services: 'Thiết kế',
  d3_nav_print: 'In 3D',
  d3_nav_about: 'Về tôi',
  d3_nav_contact: 'Liên hệ',
  d3_footer_eco: 'Hệ sinh thái',

  /* hero */
  d3_hero_eyebrow: 'MERUVA 3D & Design Studio · 02',
  d3_hero_title: 'Thiết kế thương hiệu,<br><em>3D Visualization</em><br>&amp; In 3D theo yêu cầu',
  d3_hero_desc: 'Từ ý tưởng đến vật thể thật — xây dựng hình ảnh chuyên nghiệp cho doanh nghiệp, rồi hiện thực hóa thiết kế thành sản phẩm in 3D trong 3–5 ngày. Một nơi duy nhất, trọn vòng đời sáng tạo.',
  d3_hero_btn1: 'Xem dịch vụ',
  d3_hero_btn2: 'Đặt in 3D',

  /* services header */
  d3_svc_label: 'Dịch vụ thiết kế',
  d3_svc_title: 'Những gì tôi <em>làm tốt nhất</em>',
  d3_svc_sub: 'Bốn mảng dịch vụ thiết kế cốt lõi — từ nhận diện thương hiệu đến hình ảnh 3D và truyền thông marketing. Cần in thành vật thể thật? Cuộn xuống mục In 3D.',

  /* svc 01 — branding */
  d3_s1_pri: 'Ưu tiên #1',
  d3_s1_name: 'Thiết kế Nhận Diện<br>Thương Hiệu',
  d3_s1_desc: 'Xây dựng hệ thống nhận diện thương hiệu chuyên nghiệp và nhất quán — từ logo đến toàn bộ bộ nhận diện cho doanh nghiệp mới, nhà hàng, spa, startup và shop online.',
  d3_s1_l1: 'Thiết kế logo &amp; brand mark',
  d3_s1_l2: 'Bộ nhận diện thương hiệu đầy đủ',
  d3_s1_l3: 'Name card · Hồ sơ năng lực',
  d3_s1_l4: 'Catalogue · Social media kit',
  d3_s1_l5: 'Brand guideline &amp; brand book',
  d3_s1_price: '3 – 30 triệu',
  d3_s1_unit: '/ dự án tùy quy mô',

  /* svc 02 — 3d product */
  d3_s2_pri: 'Ưu tiên #2',
  d3_s2_name: '3D Product<br>Visualization',
  d3_s2_desc: 'Tạo hình ảnh 3D sản phẩm chất lượng cao phục vụ quảng cáo, e-commerce và catalog. Chuyên mảng mỹ phẩm, nội thất, thực phẩm và máy móc công nghiệp.',
  d3_s2_l1: 'Render sản phẩm 3D high-fidelity',
  d3_s2_l2: 'Hình quảng cáo sản phẩm cho ads',
  d3_s2_l3: 'Animation sản phẩm &amp; turntable',
  d3_s2_l4: '3D mockup bao bì &amp; packaging',
  d3_s2_l5: 'Scene setup cho e-commerce',
  d3_s2_price: '500K – 5 triệu',
  d3_s2_unit: '/ sản phẩm',

  /* svc 03 — ui/ux */
  d3_s3_name: 'Website &amp; App<br>UI Design',
  d3_s3_desc: 'Thiết kế giao diện website và ứng dụng chuyên nghiệp, tập trung vào trải nghiệm người dùng. Phục vụ startup, công ty phần mềm và doanh nghiệp cần website mới.',
  d3_s3_l1: 'Landing page &amp; corporate website',
  d3_s3_l2: 'Mobile app UI (iOS &amp; Android)',
  d3_s3_l3: 'Dashboard &amp; admin panel UI',
  d3_s3_l4: 'Prototype &amp; interactive mockup',
  d3_s3_l5: 'Design system &amp; component library',
  d3_s3_price: '5 – 50 triệu',
  d3_s3_unit: '/ dự án',

  /* svc 04 — marketing */
  d3_s4_name: 'Marketing &amp;<br>Advertising Design',
  d3_s4_desc: 'Thiết kế hình ảnh quảng cáo và truyền thông marketing — từ banner digital đến ấn phẩm in ấn. Bán theo từng thiết kế hoặc gói tháng cho doanh nghiệp.',
  d3_s4_l1: 'Facebook / Instagram Ads visual',
  d3_s4_l2: 'Banner web &amp; digital out-of-home',
  d3_s4_l3: 'Poster · Brochure · Flyer',
  d3_s4_l4: 'Event visual &amp; backdrop',
  d3_s4_l5: 'Gói thiết kế tháng (retainer)',
  d3_s4_price: '200K – 2 triệu',
  d3_s4_unit: '/ thiết kế',

  /* 3d print */
  d3_print_label: 'In 3D theo yêu cầu',
  d3_print_title: 'Thiết kế. <em>In thật.</em>',
  d3_pf1_t: 'Gửi yêu cầu',
  d3_pf1_d: 'Có file STL càng tốt — chưa có, đội thiết kế dựng giúp bạn.',
  d3_pf2_t: 'Báo giá trong 24h',
  d3_pf2_d: 'Chốt vật liệu, màu sắc, kích thước và số lượng.',
  d3_pf3_t: 'In &amp; hoàn thiện',
  d3_pf3_d: 'PLA · PETG · Resin. Xử lý bề mặt, sơn phủ theo yêu cầu.',
  d3_pf4_t: 'Giao trong 3–5 ngày',
  d3_pf4_d: 'Giao tận nơi TP.HCM hoặc gửi toàn quốc.',
  d3_print_btn: 'Đặt in ngay',

  /* portfolio */
  d3_pf_title: 'Một số <em>công trình tiêu biểu</em>',
  d3_pf_sub: 'Tổng hợp dự án trải dài nhiều lĩnh vực — doanh nghiệp, F&amp;B, e-commerce, startup và giáo dục.',
  d3_flt_all: 'Tất cả',
  d3_pf_more: 'Xem thêm dự án',
  d3_i1_cat: 'Branding · Identity', d3_i1_title: 'Nhà hàng The Garden', d3_i1_sub: 'Logo · Brand book · Menu · Name card',
  d3_i2_cat: 'Branding · Startup', d3_i2_title: 'FinTech Startup Identity', d3_i2_sub: 'Logo · Brand guide · Pitch deck · Social kit',
  d3_i3_cat: 'Branding · Spa &amp; Wellness', d3_i3_title: 'Spa Lumière Rebrand', d3_i3_sub: 'Logo · Packaging · Stationery · Signage',
  d3_i4_cat: '3D · Mỹ phẩm', d3_i4_title: 'Cosmetic Product CGI', d3_i4_sub: 'Hero shot · 360° render · E-commerce asset',
  d3_i5_cat: '3D · Nội thất', d3_i5_title: 'Luxury Furniture Visualization', d3_i5_sub: 'Product animation · Catalog renders',
  d3_i6_cat: 'UI/UX · Mobile App', d3_i6_title: 'EdTech Learning Platform', d3_i6_sub: 'iOS App UI · Onboarding · Dashboard',
  d3_i7_cat: 'UI/UX · SaaS Dashboard', d3_i7_title: 'B2B Analytics Dashboard', d3_i7_sub: 'Web app UI · Design system · Prototype',
  d3_i8_cat: 'Marketing · F&amp;B', d3_i8_title: 'Coffee Brand Social Kit', d3_i8_sub: 'Instagram templates · Ads creative · Story set',
  d3_i9_cat: 'Marketing · Event', d3_i9_title: 'Cultural Festival Campaign', d3_i9_sub: 'Key visual · Poster · Banner · Backdrop',

  /* why me */
  d3_wm_label: 'Tại sao chọn tôi',
  d3_wm_title: 'Cam kết chất lượng,<br><em>tận tâm phục vụ</em>',
  d3_wm_sub: 'Không hứa hẹn suông. Không làm cho có. Mỗi dự án là một cam kết chất lượng thực sự.',
  d3_w1_t: 'Năm kinh nghiệm Freelance',
  d3_w1_d: 'Làm việc với nhiều loại hình doanh nghiệp: từ startup đến tập đoàn, từ F&amp;B đến công nghệ và giáo dục.',
  d3_w2_t: 'Thành thạo tiếng Anh',
  d3_w2_d: 'Làm việc với khách hàng quốc tế, đọc tài liệu kỹ thuật, hiểu xu hướng thiết kế toàn cầu và truyền đạt rõ ràng.',
  d3_w3_t: 'Từ concept đến vật thể thật',
  d3_w3_d: 'Tư vấn ý tưởng, nghiên cứu brand, thiết kế, in 3D và bàn giao hoàn chỉnh — không cần tự xử lý nhiều bên.',
  d3_w4_t: 'Đa lĩnh vực &amp; đa nền tảng',
  d3_w4_d: 'Kinh nghiệm doanh nghiệp, giáo dục, game, marketing. Thiết kế cho cả print, digital, 3D và interactive.',

  /* tools */
  d3_tools_label: 'Công cụ &amp; kỹ năng',

  /* contact */
  d3_c_label: 'Liên hệ',
  d3_c_title: 'Bắt đầu<br><em>dự án của bạn</em>',
  d3_c_tagline: '"Mỗi thương hiệu đều xứng đáng<br>có một diện mạo chuyên nghiệp."',
  d3_ci2_label: 'Phản hồi trong',
  d3_ci2_val: '24 giờ làm việc',
  d3_ci3_label: 'In 3D giao trong',
  d3_ci3_val: '3–5 ngày · TP.HCM &amp; toàn quốc',
  d3_ci4_label: 'Làm việc với',
  d3_ci4_val: 'Khách Việt Nam &amp; Quốc tế',
  d3_f_name: 'Họ và tên *',
  d3_f_name_ph: 'Nguyễn Văn A',
  d3_f_contact: 'Email / Số điện thoại *',
  d3_f_contact_ph: 'email@company.com hoặc 0912 345 678',
  d3_f_service: 'Dịch vụ quan tâm',
  d3_f_opt0: '— Chọn dịch vụ —',
  d3_f_opt1: 'Thiết kế nhận diện thương hiệu',
  d3_f_opt2: '3D Product Visualization',
  d3_f_opt3: 'Website / App UI Design',
  d3_f_opt4: 'Marketing &amp; Advertising Design',
  d3_f_opt5: 'In 3D theo file (PLA / PETG) · Từ 150.000₫',
  d3_f_opt6: 'In resin cao cấp · Từ 250.000₫',
  d3_f_opt7: 'Móc khóa / quà tặng custom · Từ 80.000₫',
  d3_f_opt8: 'Figure &amp; mô hình · Từ 300.000₫',
  d3_f_opt9: 'Vật phẩm sự kiện / corporate gift · Từ 120.000₫',
  d3_f_opt10: 'Gói tháng (Monthly retainer)',
  d3_f_opt11: 'Tư vấn &amp; báo giá',
  d3_f_msg: 'Mô tả yêu cầu',
  d3_f_msg_ph: 'Mô tả nhu cầu, ngành hàng, kích thước / số lượng (nếu in 3D), timeline và ngân sách dự kiến...',
  d3_f_submit: 'Gửi yêu cầu',
  d3_f_thanks: '✦  Cảm ơn bạn! MERUVA sẽ phản hồi trong 24 giờ.',

  /* footer */
  d3_footer_tagline: 'Từ đỉnh cao — chúng tôi phục vụ.',
  d3_footer_copy: '© 2026 MERUVA 3D &amp; Design Studio'
},

/* ══════════════ ENGLISH ══════════════ */
en: {
  d3_nav_services: 'Design',
  d3_nav_print: '3D Print',
  d3_nav_about: 'About',
  d3_nav_contact: 'Contact',
  d3_footer_eco: 'Ecosystem',

  d3_hero_eyebrow: 'MERUVA 3D & Design Studio · 02',
  d3_hero_title: 'Brand identity design,<br><em>3D Visualization</em><br>&amp; custom 3D printing',
  d3_hero_desc: 'From idea to physical object — we build a professional image for your business, then bring designs to life as 3D-printed products in 3–5 days. One place, the full creative lifecycle.',
  d3_hero_btn1: 'View services',
  d3_hero_btn2: 'Order a 3D print',

  d3_svc_label: 'Design services',
  d3_svc_title: 'What I <em>do best</em>',
  d3_svc_sub: 'Four core design disciplines — from brand identity to 3D visuals and marketing communications. Need it printed as a real object? Scroll down to the 3D Print section.',

  d3_s1_pri: 'Priority #1',
  d3_s1_name: 'Brand Identity<br>Design',
  d3_s1_desc: 'Build a professional, consistent brand identity system — from the logo to the full identity kit for new businesses, restaurants, spas, startups and online shops.',
  d3_s1_l1: 'Logo &amp; brand mark design',
  d3_s1_l2: 'Full brand identity kit',
  d3_s1_l3: 'Business card · Capability profile',
  d3_s1_l4: 'Catalogue · Social media kit',
  d3_s1_l5: 'Brand guideline &amp; brand book',
  d3_s1_price: '3 – 30 mil',
  d3_s1_unit: '/ project by scope',

  d3_s2_pri: 'Priority #2',
  d3_s2_name: '3D Product<br>Visualization',
  d3_s2_desc: 'Create high-quality 3D product visuals for advertising, e-commerce and catalogs. Specializing in cosmetics, furniture, food and industrial machinery.',
  d3_s2_l1: 'High-fidelity 3D product renders',
  d3_s2_l2: 'Product ad visuals for campaigns',
  d3_s2_l3: 'Product animation &amp; turntable',
  d3_s2_l4: '3D packaging mockups',
  d3_s2_l5: 'Scene setup for e-commerce',
  d3_s2_price: '500K – 5 mil',
  d3_s2_unit: '/ product',

  d3_s3_name: 'Website &amp; App<br>UI Design',
  d3_s3_desc: 'Professional website and app interface design focused on user experience. Serving startups, software companies and businesses needing a new website.',
  d3_s3_l1: 'Landing page &amp; corporate website',
  d3_s3_l2: 'Mobile app UI (iOS &amp; Android)',
  d3_s3_l3: 'Dashboard &amp; admin panel UI',
  d3_s3_l4: 'Prototype &amp; interactive mockup',
  d3_s3_l5: 'Design system &amp; component library',
  d3_s3_price: '5 – 50 mil',
  d3_s3_unit: '/ project',

  d3_s4_name: 'Marketing &amp;<br>Advertising Design',
  d3_s4_desc: 'Design advertising and marketing communications — from digital banners to print collateral. Sold per design or as monthly packages for businesses.',
  d3_s4_l1: 'Facebook / Instagram Ads visuals',
  d3_s4_l2: 'Web banners &amp; digital out-of-home',
  d3_s4_l3: 'Poster · Brochure · Flyer',
  d3_s4_l4: 'Event visuals &amp; backdrops',
  d3_s4_l5: 'Monthly design package (retainer)',
  d3_s4_price: '200K – 2 mil',
  d3_s4_unit: '/ design',

  d3_print_label: 'Custom 3D printing',
  d3_print_title: 'Design it. <em>Print it real.</em>',
  d3_pf1_t: 'Send your request',
  d3_pf1_d: 'An STL file is ideal — no file yet? Our design team builds it for you.',
  d3_pf2_t: 'Quote within 24h',
  d3_pf2_d: 'Confirm material, color, size and quantity.',
  d3_pf3_t: 'Print &amp; finish',
  d3_pf3_d: 'PLA · PETG · Resin. Surface treatment and coating on request.',
  d3_pf4_t: 'Delivered in 3–5 days',
  d3_pf4_d: 'Delivered within HCMC or shipped nationwide.',
  d3_print_btn: 'Order a print now',

  d3_pf_title: 'Selected <em>featured work</em>',
  d3_pf_sub: 'A collection of projects spanning many fields — enterprise, F&amp;B, e-commerce, startups and education.',
  d3_flt_all: 'All',
  d3_pf_more: 'View more projects',
  d3_i1_cat: 'Branding · Identity', d3_i1_title: 'The Garden Restaurant', d3_i1_sub: 'Logo · Brand book · Menu · Business card',
  d3_i2_cat: 'Branding · Startup', d3_i2_title: 'FinTech Startup Identity', d3_i2_sub: 'Logo · Brand guide · Pitch deck · Social kit',
  d3_i3_cat: 'Branding · Spa &amp; Wellness', d3_i3_title: 'Spa Lumière Rebrand', d3_i3_sub: 'Logo · Packaging · Stationery · Signage',
  d3_i4_cat: '3D · Cosmetics', d3_i4_title: 'Cosmetic Product CGI', d3_i4_sub: 'Hero shot · 360° render · E-commerce asset',
  d3_i5_cat: '3D · Furniture', d3_i5_title: 'Luxury Furniture Visualization', d3_i5_sub: 'Product animation · Catalog renders',
  d3_i6_cat: 'UI/UX · Mobile App', d3_i6_title: 'EdTech Learning Platform', d3_i6_sub: 'iOS App UI · Onboarding · Dashboard',
  d3_i7_cat: 'UI/UX · SaaS Dashboard', d3_i7_title: 'B2B Analytics Dashboard', d3_i7_sub: 'Web app UI · Design system · Prototype',
  d3_i8_cat: 'Marketing · F&amp;B', d3_i8_title: 'Coffee Brand Social Kit', d3_i8_sub: 'Instagram templates · Ads creative · Story set',
  d3_i9_cat: 'Marketing · Event', d3_i9_title: 'Cultural Festival Campaign', d3_i9_sub: 'Key visual · Poster · Banner · Backdrop',

  d3_wm_label: 'Why choose me',
  d3_wm_title: 'Committed to quality,<br><em>devoted to service</em>',
  d3_wm_sub: 'No empty promises. No going through the motions. Every project is a genuine commitment to quality.',
  d3_w1_t: 'Years of freelance experience',
  d3_w1_d: 'Working with all kinds of businesses: from startups to corporations, from F&amp;B to tech and education.',
  d3_w2_t: 'Fluent in English',
  d3_w2_d: 'Working with international clients, reading technical docs, understanding global design trends and communicating clearly.',
  d3_w3_t: 'From concept to real object',
  d3_w3_d: 'Idea consulting, brand research, design, 3D printing and complete handover — no need to juggle multiple vendors.',
  d3_w4_t: 'Multi-field &amp; multi-platform',
  d3_w4_d: 'Experience across enterprise, education, games and marketing. Designing for print, digital, 3D and interactive.',

  d3_tools_label: 'Tools &amp; skills',

  d3_c_label: 'Contact',
  d3_c_title: 'Start<br><em>your project</em>',
  d3_c_tagline: '"Every brand deserves<br>a professional look."',
  d3_ci2_label: 'Response within',
  d3_ci2_val: '24 business hours',
  d3_ci3_label: '3D print delivered in',
  d3_ci3_val: '3–5 days · HCMC &amp; nationwide',
  d3_ci4_label: 'Working with',
  d3_ci4_val: 'Vietnamese &amp; international clients',
  d3_f_name: 'Full name *',
  d3_f_name_ph: 'Your name',
  d3_f_contact: 'Email / Phone *',
  d3_f_contact_ph: 'email@company.com or +84 912 345 678',
  d3_f_service: 'Service of interest',
  d3_f_opt0: '— Select a service —',
  d3_f_opt1: 'Brand identity design',
  d3_f_opt2: '3D Product Visualization',
  d3_f_opt3: 'Website / App UI Design',
  d3_f_opt4: 'Marketing &amp; Advertising Design',
  d3_f_opt5: '3D print from file (PLA / PETG) · From 150,000₫',
  d3_f_opt6: 'Premium resin print · From 250,000₫',
  d3_f_opt7: 'Custom keychain / gift · From 80,000₫',
  d3_f_opt8: 'Figure &amp; model · From 300,000₫',
  d3_f_opt9: 'Event item / corporate gift · From 120,000₫',
  d3_f_opt10: 'Monthly retainer',
  d3_f_opt11: 'Consultation &amp; quote',
  d3_f_msg: 'Describe your request',
  d3_f_msg_ph: 'Describe your needs, industry, size / quantity (if 3D printing), timeline and expected budget...',
  d3_f_submit: 'Send request',
  d3_f_thanks: '✦  Thank you! MERUVA will respond within 24 hours.',

  d3_footer_tagline: 'From the summit — we serve.',
  d3_footer_copy: '© 2026 MERUVA 3D &amp; Design Studio'
},

/* ══════════════ 日本語 ══════════════ */
ja: {
  d3_nav_services: 'デザイン',
  d3_nav_print: '3Dプリント',
  d3_nav_about: '私について',
  d3_nav_contact: 'お問い合わせ',
  d3_footer_eco: 'エコシステム',

  d3_hero_eyebrow: 'MERUVA 3D & Design Studio · 02',
  d3_hero_title: 'ブランドデザイン、<br><em>3Dビジュアライゼーション</em><br>&amp; オーダー3Dプリント',
  d3_hero_desc: 'アイデアから実物へ — ビジネスのプロフェッショナルなイメージを構築し、デザインを3Dプリント製品として3〜5日で実現します。一箇所で、創造の全工程を。',
  d3_hero_btn1: 'サービスを見る',
  d3_hero_btn2: '3Dプリントを注文',

  d3_svc_label: 'デザインサービス',
  d3_svc_title: '私が<em>最も得意なこと</em>',
  d3_svc_sub: '4つの中核デザイン領域 — ブランドアイデンティティから3Dビジュアル、マーケティング表現まで。実物としてプリントが必要ですか？3Dプリントのセクションへスクロール。',

  d3_s1_pri: '優先 #1',
  d3_s1_name: 'ブランド<br>アイデンティティ設計',
  d3_s1_desc: 'プロフェッショナルで一貫したブランドアイデンティティシステムを構築 — ロゴから、新規ビジネス・レストラン・スパ・スタートアップ・オンラインショップ向けの完全な識別キットまで。',
  d3_s1_l1: 'ロゴ &amp; ブランドマーク設計',
  d3_s1_l2: '完全なブランドアイデンティティキット',
  d3_s1_l3: '名刺 · 会社概要',
  d3_s1_l4: 'カタログ · ソーシャルメディアキット',
  d3_s1_l5: 'ブランドガイドライン &amp; ブランドブック',
  d3_s1_price: '300万 – 3,000万₫',
  d3_s1_unit: '/ 規模に応じたプロジェクト',

  d3_s2_pri: '優先 #2',
  d3_s2_name: '3Dプロダクト<br>ビジュアライゼーション',
  d3_s2_desc: '広告・EC・カタログ向けの高品質な3D製品ビジュアルを制作。化粧品・家具・食品・産業機械を専門としています。',
  d3_s2_l1: '高精細3D製品レンダリング',
  d3_s2_l2: '広告用の製品ビジュアル',
  d3_s2_l3: '製品アニメーション &amp; ターンテーブル',
  d3_s2_l4: '3Dパッケージモックアップ',
  d3_s2_l5: 'EC向けシーンセットアップ',
  d3_s2_price: '50万 – 500万₫',
  d3_s2_unit: '/ 製品',

  d3_s3_name: 'ウェブ &amp; アプリ<br>UIデザイン',
  d3_s3_desc: 'ユーザー体験を重視したプロフェッショナルなウェブ・アプリのUIデザイン。スタートアップ、ソフトウェア企業、新しいウェブサイトが必要な企業向け。',
  d3_s3_l1: 'ランディングページ &amp; 企業サイト',
  d3_s3_l2: 'モバイルアプリUI (iOS &amp; Android)',
  d3_s3_l3: 'ダッシュボード &amp; 管理画面UI',
  d3_s3_l4: 'プロトタイプ &amp; インタラクティブモックアップ',
  d3_s3_l5: 'デザインシステム &amp; コンポーネントライブラリ',
  d3_s3_price: '500万 – 5,000万₫',
  d3_s3_unit: '/ プロジェクト',

  d3_s4_name: 'マーケティング &amp;<br>広告デザイン',
  d3_s4_desc: '広告とマーケティング表現のデザイン — デジタルバナーから印刷物まで。デザイン単位、または企業向け月額パッケージで提供。',
  d3_s4_l1: 'Facebook / Instagram 広告ビジュアル',
  d3_s4_l2: 'ウェブバナー &amp; デジタルサイネージ',
  d3_s4_l3: 'ポスター · パンフレット · チラシ',
  d3_s4_l4: 'イベントビジュアル &amp; バックドロップ',
  d3_s4_l5: '月額デザインパッケージ（リテイナー）',
  d3_s4_price: '20万 – 200万₫',
  d3_s4_unit: '/ デザイン',

  d3_print_label: 'オーダー3Dプリント',
  d3_print_title: 'デザインを。<em>実物に。</em>',
  d3_pf1_t: 'リクエストを送信',
  d3_pf1_d: 'STLファイルがあると理想的 — なくても、デザインチームが作成します。',
  d3_pf2_t: '24時間以内に見積もり',
  d3_pf2_d: '素材・色・サイズ・数量を確定。',
  d3_pf3_t: 'プリント &amp; 仕上げ',
  d3_pf3_d: 'PLA · PETG · レジン。ご要望に応じて表面処理・塗装。',
  d3_pf4_t: '3〜5日でお届け',
  d3_pf4_d: 'ホーチミン市内へ配達、または全国へ発送。',
  d3_print_btn: '今すぐ注文',

  d3_pf_title: '代表的な<em>制作実績</em>',
  d3_pf_sub: '多分野にわたるプロジェクト集 — 企業、F&amp;B、EC、スタートアップ、教育。',
  d3_flt_all: 'すべて',
  d3_pf_more: 'もっと見る',
  d3_i1_cat: 'Branding · Identity', d3_i1_title: 'The Garden レストラン', d3_i1_sub: 'ロゴ · ブランドブック · メニュー · 名刺',
  d3_i2_cat: 'Branding · Startup', d3_i2_title: 'FinTech スタートアップ アイデンティティ', d3_i2_sub: 'ロゴ · ブランドガイド · ピッチデック · ソーシャルキット',
  d3_i3_cat: 'Branding · Spa &amp; Wellness', d3_i3_title: 'Spa Lumière リブランド', d3_i3_sub: 'ロゴ · パッケージ · ステーショナリー · サイン',
  d3_i4_cat: '3D · 化粧品', d3_i4_title: 'コスメ製品 CGI', d3_i4_sub: 'ヒーローショット · 360°レンダー · EC素材',
  d3_i5_cat: '3D · 家具', d3_i5_title: 'ラグジュアリー家具ビジュアライゼーション', d3_i5_sub: '製品アニメーション · カタログレンダー',
  d3_i6_cat: 'UI/UX · モバイルアプリ', d3_i6_title: 'EdTech 学習プラットフォーム', d3_i6_sub: 'iOSアプリUI · オンボーディング · ダッシュボード',
  d3_i7_cat: 'UI/UX · SaaS ダッシュボード', d3_i7_title: 'B2B アナリティクス ダッシュボード', d3_i7_sub: 'ウェブアプリUI · デザインシステム · プロトタイプ',
  d3_i8_cat: 'Marketing · F&amp;B', d3_i8_title: 'コーヒーブランド ソーシャルキット', d3_i8_sub: 'Instagramテンプレート · 広告クリエイティブ · ストーリーセット',
  d3_i9_cat: 'Marketing · Event', d3_i9_title: '文化フェスティバル キャンペーン', d3_i9_sub: 'キービジュアル · ポスター · バナー · バックドロップ',

  d3_wm_label: '私が選ばれる理由',
  d3_wm_title: '品質へのこだわり、<br><em>真心のサービス</em>',
  d3_wm_sub: '口先だけの約束はしません。形だけの仕事もしません。すべてのプロジェクトが本物の品質へのコミットメントです。',
  d3_w1_t: 'フリーランス経験年数',
  d3_w1_d: 'スタートアップから大企業まで、F&amp;Bからテック・教育まで、さまざまな業種と協働。',
  d3_w2_t: '英語に堪能',
  d3_w2_d: '海外クライアントとの協働、技術資料の読解、グローバルなデザイントレンドの理解と明確なコミュニケーション。',
  d3_w3_t: 'コンセプトから実物まで',
  d3_w3_d: 'アイデア相談、ブランド調査、デザイン、3Dプリント、完全な納品まで — 複数の業者を抱える必要はありません。',
  d3_w4_t: '多分野 &amp; マルチプラットフォーム',
  d3_w4_d: '企業・教育・ゲーム・マーケティングの経験。印刷・デジタル・3D・インタラクティブすべてのデザイン。',

  d3_tools_label: 'ツール &amp; スキル',

  d3_c_label: 'お問い合わせ',
  d3_c_title: 'あなたの<br><em>プロジェクトを始める</em>',
  d3_c_tagline: '「すべてのブランドには<br>プロフェッショナルな佇まいがふさわしい。」',
  d3_ci2_label: '返信時間',
  d3_ci2_val: '営業時間24時間以内',
  d3_ci3_label: '3Dプリント納期',
  d3_ci3_val: '3〜5日 · ホーチミン市 &amp; 全国',
  d3_ci4_label: '対応',
  d3_ci4_val: 'ベトナム &amp; 海外のお客様',
  d3_f_name: 'お名前 *',
  d3_f_name_ph: 'お名前',
  d3_f_contact: 'メール / 電話番号 *',
  d3_f_contact_ph: 'email@company.com または +84 912 345 678',
  d3_f_service: 'ご希望のサービス',
  d3_f_opt0: '— サービスを選択 —',
  d3_f_opt1: 'ブランドアイデンティティ設計',
  d3_f_opt2: '3D Product Visualization',
  d3_f_opt3: 'ウェブ / アプリ UIデザイン',
  d3_f_opt4: 'マーケティング &amp; 広告デザイン',
  d3_f_opt5: 'ファイルから3Dプリント (PLA / PETG) · 150,000₫〜',
  d3_f_opt6: '高級レジンプリント · 250,000₫〜',
  d3_f_opt7: 'カスタムキーホルダー / ギフト · 80,000₫〜',
  d3_f_opt8: 'フィギュア &amp; モデル · 300,000₫〜',
  d3_f_opt9: 'イベント用品 / 法人ギフト · 120,000₫〜',
  d3_f_opt10: '月額リテイナー',
  d3_f_opt11: '相談 &amp; 見積もり',
  d3_f_msg: 'ご要望の詳細',
  d3_f_msg_ph: 'ニーズ、業種、サイズ / 数量（3Dプリントの場合）、スケジュール、予算をご記入ください...',
  d3_f_submit: 'リクエストを送信',
  d3_f_thanks: '✦  ありがとうございます！MERUVAより24時間以内にご返信します。',

  d3_footer_tagline: '頂から — 私たちは仕えます。',
  d3_footer_copy: '© 2026 MERUVA 3D &amp; Design Studio'
}

}; /* end MERUVA3D_LANG */
